from typing import Any, Optional

def displayAstrometry(refCat: Optional[Any] = ..., sourceCat: Optional[Any] = ..., distortedCentroidKey: Optional[Any] = ..., bbox: Optional[Any] = ..., exposure: Optional[Any] = ..., matches: Optional[Any] = ..., frame: int = ..., title: str = ..., pause: bool = ...) -> None: ...
def plotAstrometry(matches: Any, refCat: Optional[Any] = ..., sourceCat: Optional[Any] = ..., refMarker: str = ..., refColor: str = ..., sourceMarker: str = ..., sourceColor: str = ..., matchColor: str = ...): ...
