import lsst.pipe.base as pexConfig
import lsst.pipe.base as pipeBase
from typing import Any, Optional

class FitAffineWcsConfig(pexConfig.Config): ...

class FitAffineWcsTask(pipeBase.Task):
    ConfigClass: Any = ...
    def fitWcs(self, matches: Any, initWcs: Any, bbox: Optional[Any] = ..., refCat: Optional[Any] = ..., sourceCat: Optional[Any] = ..., exposure: Optional[Any] = ...): ...

class TransformedSkyWcsMaker:
    frameDict: Any = ...
    frameIdxs: Any = ...
    frameMin: Any = ...
    frameMax: Any = ...
    mapFrom: Any = ...
    mapTo: Any = ...
    lastMapBeforeSky: Any = ...
    origin: Any = ...
    def __init__(self, inputSkyWcs: Any) -> None: ...
    def makeWcs(self, crvalOffset: Any, affMatrix: Any): ...
