import lsst.afw.display
from typing import Any, Optional

class FitSipDistortionConfig(lsst.pex.config.Config):
    order: Any = ...
    numRejIter: Any = ...
    rejSigma: Any = ...
    nClipMin: Any = ...
    nClipMax: Any = ...
    maxScatterArcsec: Any = ...
    refUncertainty: Any = ...
    nGridX: Any = ...
    nGridY: Any = ...
    gridBorder: Any = ...

class FitSipDistortionTask(lsst.pipe.base.Task):
    ConfigClass: Any = ...
    outlierRejectionCtrl: Any = ...
    def __init__(self, **kwargs: Any) -> None: ...
    def fitWcs(self, matches: Any, initWcs: Any, bbox: Optional[Any] = ..., refCat: Optional[Any] = ..., sourceCat: Optional[Any] = ..., exposure: Optional[Any] = ...): ...
    def display(self, revFitter: Any, exposure: Optional[Any] = ..., bbox: Optional[Any] = ..., frame: int = ..., pause: bool = ...): ...
    def makeInitialWcs(self, matches: Any, wcs: Any): ...
