from ..datastore import DatastoreTransaction
from ._butlerUri import ButlerURI
from .utils import NoTransaction
from typing import Any, Optional, Union

class ButlerFileURI(ButlerURI):
    transferModes: Any = ...
    transferDefault: str = ...
    isLocal: bool = ...
    @property
    def ospath(self) -> str: ...
    def exists(self) -> bool: ...
    def size(self) -> int: ...
    def remove(self) -> None: ...
    def relative_to(self, other: ButlerURI) -> Optional[str]: ...
    def read(self, size: int=...) -> bytes: ...
    def write(self, data: bytes, overwrite: bool=...) -> None: ...
    def mkdir(self) -> None: ...
    def transfer_from(self, src: ButlerURI, transfer: str, overwrite: bool=..., transaction: Optional[Union[DatastoreTransaction, NoTransaction]]=...) -> None: ...
