import requests
from ..datastore import DatastoreTransaction
from ._butlerUri import ButlerURI
from .utils import NoTransaction
from typing import Optional, Union

class ButlerHttpURI(ButlerURI):
    @property
    def session(self) -> requests.Session: ...
    def exists(self) -> bool: ...
    def size(self) -> int: ...
    def mkdir(self) -> None: ...
    def remove(self) -> None: ...
    def read(self, size: int=...) -> bytes: ...
    def write(self, data: bytes, overwrite: bool=...) -> None: ...
    def transfer_from(self, src: ButlerURI, transfer: str=..., overwrite: bool=..., transaction: Optional[Union[DatastoreTransaction, NoTransaction]]=...) -> None: ...
