import boto3
from ..location import Location
from ._butlerUri import ButlerURI
from typing import Optional, Tuple, Union

def getS3Client() -> boto3.client: ...
def s3CheckFileExists(path: Union[Location, ButlerURI, str], bucket: Optional[str]=..., client: Optional[boto3.client]=...) -> Tuple[bool, int]: ...
def bucketExists(bucketName: str, client: Optional[boto3.client]=...) -> bool: ...
def setAwsEnvCredentials(accessKeyId: str=..., secretAccessKey: str=...) -> bool: ...
def unsetAwsEnvCredentials() -> None: ...
