from pathlib import PurePath
from typing import Any, Callable, Iterator, Union

def os2posix(ospath: str) -> str: ...
def posix2os(posix: Union[PurePath, str]) -> str: ...

class NoTransaction:
    def __init__(self) -> None: ...
    def undoWith(self, name: str, undoFunc: Callable, *args: Any, **kwargs: Any) -> Iterator[None]: ...
