from .catalogCalculation import CatalogCalculationPlugin, CatalogCalculationPluginConfig
from typing import Any, Optional

class CatalogCalculationClassificationConfig(CatalogCalculationPluginConfig):
    fluxRatio: Any = ...
    modelErrFactor: Any = ...
    psfErrFactor: Any = ...

class CatalogCalculationClassificationPlugin(CatalogCalculationPlugin):
    ConfigClass: Any = ...
    @classmethod
    def getExecutionOrder(cls): ...
    keyProbability: Any = ...
    keyFlag: Any = ...
    def __init__(self, config: Any, name: Any, schema: Any, metadata: Any) -> None: ...
    def calculate(self, measRecord: Any) -> None: ...
    def fail(self, measRecord: Any, error: Optional[Any] = ...) -> None: ...
