from .catalogCalculation import CatalogCalculationPlugin, CatalogCalculationPluginConfig
from typing import Any, Optional

class CatalogCalculationFootprintAreaConfig(CatalogCalculationPluginConfig): ...

class CatalogCalculationFootprintAreaPlugin(CatalogCalculationPlugin):
    ConfigClass: Any = ...
    @classmethod
    def getExecutionOrder(cls): ...
    key: Any = ...
    def __init__(self, config: Any, name: Any, schema: Any, metadata: Any) -> None: ...
    def calculate(self, measRecord: Any) -> None: ...
    def fail(self, measRecord: Any, error: Optional[Any] = ...) -> None: ...
