import lsst.pex.config
from typing import Any, Optional

class BasePluginConfig(lsst.pex.config.Config): ...

class BasePlugin:
    CENTROID_ORDER: float = ...
    SHAPE_ORDER: float = ...
    FLUX_ORDER: float = ...
    APCORR_ORDER: float = ...
    DEFAULT_CATALOGCALCULATION: float = ...
    ConfigClass: Any = ...
    @classmethod
    def getExecutionOrder(cls) -> None: ...
    config: Any = ...
    name: Any = ...
    logName: Any = ...
    def __init__(self, config: Any, name: Any, logName: Optional[Any] = ...) -> None: ...
    def getLogName(self): ...
    def fail(self, measRecord: Any, error: Optional[Any] = ...) -> None: ...
    @staticmethod
    def getTransformClass(): ...
