from typing import Any

class MeasurementTransform:
    name: Any = ...
    config: Any = ...
    def __init__(self, config: Any, name: Any, mapper: Any) -> None: ...
    def __call__(self, inputCatalog: Any, outputCatalog: Any, wcs: Any, photoCalib: Any) -> None: ...

class NullTransform(MeasurementTransform):
    def __call__(self, inputCatalog: Any, outputCatalog: Any, wcs: Any, photoCalib: Any) -> None: ...

class PassThroughTransform(MeasurementTransform):
    def __init__(self, config: Any, name: Any, mapper: Any) -> None: ...
    def __call__(self, inputCatalog: Any, outputCatalog: Any, wcs: Any, photoCalib: Any) -> None: ...

class SimpleCentroidTransform(MeasurementTransform):
    coordKey: Any = ...
    def __init__(self, config: Any, name: Any, mapper: Any) -> None: ...
    def __call__(self, inputCatalog: Any, outputCatalog: Any, wcs: Any, photoCalib: Any) -> None: ...
