from typing import Any, Optional

def merge_headers(headers: Any, mode: str = ..., sort: bool = ..., first: Optional[Any] = ..., last: Optional[Any] = ...): ...
def fix_header(header: Any, search_path: Optional[Any] = ..., translator_class: Optional[Any] = ..., filename: Optional[Any] = ...): ...
