import lsst.pex.config as pexConfig
from typing import Any

class AuthInfoConfig(pexConfig.Config):
    host: Any = ...
    user: Any = ...
    password: Any = ...
    port: Any = ...

class AuthDatabaseConfig(pexConfig.Config):
    authInfo: Any = ...

class AuthConfig(pexConfig.Config):
    database: Any = ...
