import lsst.pex.config as pexConfig
from typing import Any

class CondorDataConfig(pexConfig.Config):
    localScratch: Any = ...

class TemplateConfig(pexConfig.Config):
    keywords: Any = ...
    inputFile: Any = ...
    outputFile: Any = ...

class GlideinConfig(pexConfig.Config):
    template: Any = ...

class CondorWorkflowConfig(pexConfig.Config):
    condorData: Any = ...
    glidein: Any = ...
