import lsst.pex.config as pexConfig
from typing import Any

class AuthInfo(pexConfig.Config):
    host: Any = ...
    port: Any = ...

class RunCleanup(pexConfig.Config):
    daysFirstNotice: Any = ...
    daysFinalNotice: Any = ...

class DatabaseSystem(pexConfig.Config):
    authInfo: Any = ...
    runCleanup: Any = ...

class ProductionDatabaseConfig(pexConfig.Config):
    globalDbName: Any = ...

class WorkflowDatabaseConfig(pexConfig.Config):
    dbName: Any = ...

dbTypemap: Any

class DatabaseConfig(pexConfig.Config):
    name: Any = ...
    system: Any = ...
    configurationClass: Any = ...
    configuration: Any = ...
