import lsst.pex.config as pexConfig
from typing import Any

class DirectoryConfig(pexConfig.Config):
    defaultRoot: Any = ...
    runDirPattern: Any = ...
    workDir: Any = ...
    inputDir: Any = ...
    outputDir: Any = ...
    updateDir: Any = ...
    scratchDir: Any = ...
