import lsst.pex.config as pexConfig
from lsst.ctrl.orca.config.DirectoryConfig import DirectoryConfig as DirectoryConfig
from typing import Any

class AppStageConfig(pexConfig.Config):
    parallelClass: Any = ...
    stageConfig: Any = ...

class ExecuteConfig(pexConfig.Config):
    dir: Any = ...
    environment: Any = ...
    task: Any = ...

class FrameworkConfig(pexConfig.Config):
    script: Any = ...
    type: Any = ...
    environment: Any = ...

class DeployConfig(pexConfig.Config):
    processesOnNode: Any = ...

class PipelineDefinitionConfig(pexConfig.Config):
    execute: Any = ...
    framework: Any = ...

class PipelineConfig(pexConfig.Config):
    definition: Any = ...
    deploy: Any = ...
    runCount: Any = ...
