import lsst.pex.config as pexConfig
from typing import Any

class FrameworkConfig(pexConfig.Config):
    script: Any = ...
    type: Any = ...
    environment: Any = ...

class PipelineDefinitionConfig(pexConfig.Config):
    framework: Any = ...
