import lsst.pex.config as pexConfig
from lsst.ctrl.orca.config.DirectoryConfig import DirectoryConfig as DirectoryConfig
from typing import Any

class HwConfig(pexConfig.Config):
    nodeCount: Any = ...
    minCoresPerNode: Any = ...
    maxCoresPerNode: Any = ...
    minRamPerNode: Any = ...
    maxRamPerNode: Any = ...

class DeployConfig(pexConfig.Config):
    defaultDomain: Any = ...
    nodes: Any = ...

class PlatformConfig(pexConfig.Config):
    dir: Any = ...
    hw: Any = ...
    deploy: Any = ...
