import lsst.pex.config as pexConfig
from typing import Any

class ProductionLevelConfig(pexConfig.Config):
    configurationClass: Any = ...

class Production(pexConfig.Config):
    shortName: Any = ...
    repositoryDirectory: Any = ...
    configCheckCare: Any = ...
    logThreshold: Any = ...
    configuration: Any = ...

class ProductionConfig(pexConfig.Config):
    production: Any = ...
    database: Any = ...
    workflow: Any = ...
    configCheckCare: Any = ...
    configurationClass: Any = ...
