import lsst.pex.config as pexConfig
from typing import Any

class ScriptTemplateConfig(pexConfig.Config):
    inputFile: Any = ...
    keywords: Any = ...
    outputFile: Any = ...

class JobTemplateConfig(pexConfig.Config):
    script: Any = ...
    condor: Any = ...

class ScriptConfig(pexConfig.Config):
    script: Any = ...

class DagGeneratorConfig(pexConfig.Config):
    dagName: Any = ...
    script: Any = ...
    inputFile: Any = ...
    idsPerJob: Any = ...

class SitesConfig(pexConfig.Config):
    inputFile: Any = ...
    outputFile: Any = ...
    keywords: Any = ...

class DaxGeneratorConfig(pexConfig.Config):
    daxName: Any = ...
    script: Any = ...
    inputFile: Any = ...
    sites: Any = ...
    transformFile: Any = ...

typemap: Any

class TaskConfig(pexConfig.Config):
    scriptDir: Any = ...
    preScript: Any = ...
    preJob: Any = ...
    postJob: Any = ...
    workerJob: Any = ...
    generator: Any = ...
