import lsst.pex.config as pexConfig
from typing import Any

typemap: Any

class WorkflowConfig(pexConfig.Config):
    shortName: Any = ...
    platform: Any = ...
    configurationType: Any = ...
    configurationClass: Any = ...
    configuration: Any = ...
    database: Any = ...
    task: Any = ...
    monitor: Any = ...
