from lsst.ip.isr import IsrTask
from typing import Any, Optional

class CfhtIsrTaskConfig(IsrTask.ConfigClass):
    safe: Any = ...
    def setDefaults(self) -> None: ...

class CfhtIsrTask(IsrTask):
    ConfigClass: Any = ...
    def run(self, ccdExposure: Any, bias: Optional[Any] = ..., linearizer: Optional[Any] = ..., dark: Optional[Any] = ..., flat: Optional[Any] = ..., defects: Optional[Any] = ..., fringes: Optional[Any] = ..., bfKernel: Optional[Any] = ..., **kwds: Any): ...
