from lsst.obs.base import FitsRawFormatterBase
from typing import Any

class MegaPrimeRawFormatter(FitsRawFormatterBase):
    translatorClass: Any = ...
    filterDefinitions: Any = ...
    def getDetector(self, id: Any): ...
    def readMetadata(self): ...
    def readImage(self): ...
