from ..image.multiband import MultibandTripleBase
from typing import Any, Optional

class MultibandExposure(MultibandTripleBase):
    def __init__(self, filters: Any, image: Any, mask: Any, variance: Any, psfs: Optional[Any] = ...) -> None: ...
    @staticmethod
    def fromExposures(filters: Any, singles: Any): ...
    @staticmethod
    def fromArrays(filters: Any, image: Any, mask: Any, variance: Any, bbox: Optional[Any] = ...): ...
    @staticmethod
    def fromKwargs(filters: Any, filterKwargs: Any, singleType: Any = ..., **kwargs: Any): ...
    @staticmethod
    def fromButler(butler: Any, filters: Any, filterKwargs: Any, *args: Any, **kwargs: Any): ...
    def computePsfKernelImage(self, position: Optional[Any] = ...): ...
    def computePsfImage(self, position: Optional[Any] = ...): ...
