import lsst.afw.geom as pipeBase
from typing import Any

class CpDarkConnections(pipeBase.PipelineTaskConnections):
    inputExp: Any = ...
    outputExp: Any = ...

class CpDarkTaskConfig(pipeBase.PipelineTaskConfig):
    psfFwhm: Any = ...
    psfSize: Any = ...
    crGrow: Any = ...
    repair: Any = ...

class CpDarkTask(pipeBase.PipelineTask, pipeBase.CmdLineTask):
    ConfigClass: Any = ...
    def __init__(self, **kwargs: Any) -> None: ...
    def run(self, inputExp: Any): ...
