import lsst.afw.detection as pipeBase
from typing import Any

class CpFringeConnections(pipeBase.PipelineTaskConnections):
    inputExp: Any = ...
    outputExp: Any = ...

class CpFringeTaskConfig(pipeBase.PipelineTaskConfig):
    stats: Any = ...
    subtractBackground: Any = ...
    detection: Any = ...
    detectSigma: Any = ...
    def setDefaults(self) -> None: ...

class CpFringeTask(pipeBase.PipelineTask, pipeBase.CmdLineTask):
    ConfigClass: Any = ...
    def __init__(self, **kwargs: Any) -> None: ...
    def run(self, inputExp: Any): ...
