from typing import Any, Optional

def getBOTphotodiodeData(dataRef: Any, dataPath: str = ..., logger: Optional[Any] = ...): ...

class PhotodiodeData:
    def __init__(self, filename: Any) -> None: ...
    def getCharge(self, subtractBaseline: bool = ...): ...
