import lsst.eotest.sensor as pexConfig
import lsst.eotest.sensor as pipeBase
from typing import Any, Optional

class RunEotestConfig(pexConfig.Config):
    ccdKey: Any = ...
    fe55: Any = ...
    doFe55: Any = ...
    readNoise: Any = ...
    doReadNoise: Any = ...
    brightPixels: Any = ...
    doBrightPixels: Any = ...
    darkPixels: Any = ...
    doDarkPixels: Any = ...
    traps: Any = ...
    doTraps: Any = ...
    cte: Any = ...
    doCTE: Any = ...
    ptc: Any = ...
    doPTC: Any = ...
    flatPair: Any = ...
    doFlatPair: Any = ...
    eotestOutputPath: Any = ...
    requireAllEOTests: Any = ...
    flatPairMaxPdFracDev: Any = ...
    def setDefaults(self) -> None: ...
    def validate(self) -> None: ...

class RunEotestTask(pipeBase.CmdLineTask):
    ConfigClass: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def makeEotestReport(self, butler: Any) -> None: ...
    def runEotestDirect(self, butler: Any, run: Optional[Any] = ...) -> None: ...
