from .ellipsesLib import *
from typing import Any, Optional

Separable: Any

class EllipseMatplotlibInterface:
    scale: Any = ...
    patch: Any = ...
    def __init__(self, ellipse: Any, scale: float = ..., **kwds: Any) -> None: ...
    def __getattr__(self, name: Any): ...
    def update(self, show: bool = ..., rescale: bool = ...) -> None: ...

def Ellipse_plot(self, axes: Optional[Any] = ..., scale: float = ..., show: bool = ..., rescale: bool = ..., **kwds: Any): ...
