import lsst.pex.config as pexConfig
from typing import Any

class AllocatedPlatformConfig(pexConfig.Config):
    queue: Any = ...
    email: Any = ...
    scratchDirectory: Any = ...
    loginHostName: Any = ...
    utilityPath: Any = ...
    totalCoresPerNode: Any = ...
    glideinShutdown: Any = ...

class AllocationConfig(pexConfig.Config):
    platform: Any = ...
