from .condorConfig import CondorConfig as CondorConfig
from .condorInfoConfig import CondorInfoConfig as CondorInfoConfig
from .templateWriter import TemplateWriter as TemplateWriter
from lsst.ctrl.execute import envString as envString
from typing import Any

class Configurator:
    opts: Any = ...
    setup_using: Any = ...
    manager: Any = ...
    defaults: Any = ...
    platform: Any = ...
    commandLineDefaults: Any = ...
    runid: Any = ...
    def __init__(self, opts: Any, configFileName: Any) -> None: ...
    def getGenericConfigFileName(self): ...
    def createRunId(self): ...
    def getSetupPackages(self): ...
    def load(self, name: Any) -> None: ...
    outputFileName: Any = ...
    def createConfiguration(self, input: Any): ...
    def isVerbose(self): ...
    def getParameter(self, value: Any): ...
    def getRunId(self): ...
