from lsst.ctrl.execute import envString as envString
from lsst.ctrl.execute.allocationConfig import AllocationConfig as AllocationConfig
from lsst.ctrl.execute.condorInfoConfig import CondorInfoConfig as CondorInfoConfig
from typing import Any

class QCommand:
    remoteLoginCmd: str = ...
    remoteCopyCmd: str = ...
    userName: Any = ...
    hostName: Any = ...
    utilityPath: Any = ...
    def __init__(self, platform: Any) -> None: ...
    def runCommand(self, command: Any): ...
