from typing import Any

class RunOrcaParser:
    defaults: Any = ...
    args: Any = ...
    def __init__(self, basename: Any) -> None: ...
    def parseArgs(self, basename: Any): ...
    def getArgs(self): ...
