from lsst.ctrl.execute.allocator import Allocator as Allocator
from typing import Any

class SlurmPlugin(Allocator):
    def submit(self, platform: Any, platformPkgDir: Any) -> None: ...
    allocationFileName: Any = ...
    def loadSlurm(self, name: Any, platformPkgDir: Any) -> None: ...
    def createAllocationFile(self, input: Any): ...
