from lsst.meas.algorithms import BaseSourceSelectorTask
from typing import Any, Optional

class PsfexStarSelectorConfig(BaseSourceSelectorTask.ConfigClass):
    fluxName: Any = ...
    fluxErrName: Any = ...
    minFwhm: Any = ...
    maxFwhm: Any = ...
    maxFwhmVariability: Any = ...
    maxbad: Any = ...
    maxbadflag: Any = ...
    maxellip: Any = ...
    minsn: Any = ...
    def validate(self) -> None: ...
    badFlags: Any = ...
    def setDefaults(self) -> None: ...

class EventHandler:
    axes: Any = ...
    xs: Any = ...
    ys: Any = ...
    x: Any = ...
    y: Any = ...
    frames: Any = ...
    cid: Any = ...
    def __init__(self, axes: Any, xs: Any, ys: Any, x: Any, y: Any, frames: Any = ...) -> None: ...
    def __call__(self, ev: Any) -> None: ...

class PsfexStarSelectorTask(BaseSourceSelectorTask):
    ConfigClass: Any = ...
    usesMatches: bool = ...
    def selectSources(self, sourceCat: Any, matches: Optional[Any] = ..., exposure: Optional[Any] = ...): ...
