from typing import Any

class ExposureIdInfo:
    expId: Any = ...
    expBits: Any = ...
    maxBits: Any = ...
    def __init__(self, expId: int = ..., expBits: int = ..., maxBits: int = ...) -> None: ...
    @property
    def unusedBits(self): ...
