import collections.abc
from typing import Any

class FilterDefinitionCollection(collections.abc.Sequence):
    def __init__(self, *filters: Any) -> None: ...
    def __getitem__(self, key: Any): ...
    def __len__(self): ...
    def defineFilters(self) -> None: ...
    @classmethod
    def reset(cls) -> None: ...

class FilterDefinition:
    physical_filter: str
    lambdaEff: float
    band: str = ...
    afw_name: str = ...
    lambdaMin: float = ...
    lambdaMax: float = ...
    alias: set = ...
    def __post_init__(self) -> None: ...
    def defineFilter(self) -> None: ...
    def __init__(self, physical_filter: Any, lambdaEff: Any, band: Any, afw_name: Any, lambdaMin: Any, lambdaMax: Any, alias: Any) -> None: ...
