import abc
from lsst.daf.butler import Registry as Registry, RegistryConfig as RegistryConfig
from lsst.obs.base import Instrument as Instrument
from lsst.obs.base.gen2to3 import TranslatorFactory as TranslatorFactory
from typing import Any

class InstrumentTestData:
    name: str
    nDetectors: int
    firstDetectorName: str
    physical_filters: None
    def __init__(self, name: Any, nDetectors: Any, firstDetectorName: Any, physical_filters: Any) -> None: ...

class InstrumentTests(metaclass=abc.ABCMeta):
    data: Any = ...
    instrument: Any = ...
    def test_name(self) -> None: ...
    def test_getCamera(self) -> None: ...
    def test_register(self) -> None: ...
    def testMakeTranslatorFactory(self) -> None: ...
