from typing import Any, Optional

class MakeRawVisitInfoViaObsInfo:
    metadataTranslator: Any = ...
    log: Any = ...
    doStripHeader: Any = ...
    def __init__(self, log: Optional[Any] = ..., doStripHeader: bool = ...) -> None: ...
    def __call__(self, md: Any, exposureId: Optional[Any] = ...): ...
    @staticmethod
    def observationInfo2visitInfo(obsInfo: Any, log: Optional[Any] = ...): ...
