import abc
from typing import Any, Optional

class MapperTests(metaclass=abc.ABCMeta):
    mapper_data: Any = ...
    def setUp_mapper(self, output: Optional[Any] = ..., path_to_raw: Optional[Any] = ..., keys: Optional[Any] = ..., query_format: Optional[Any] = ..., queryMetadata: Optional[Any] = ..., metadata_output_path: Optional[Any] = ..., map_python_type: Optional[Any] = ..., map_python_std_type: Optional[Any] = ..., map_cpp_type: Optional[Any] = ..., map_storage_name: Optional[Any] = ..., raw_filename: Optional[Any] = ..., default_level: Optional[Any] = ..., raw_levels: Optional[Any] = ..., test_config_metadata: bool = ...) -> None: ...
    def test_map_config_data(self) -> None: ...
    def test_map_metadata_data(self) -> None: ...
    def test_keys(self) -> None: ...
    def test_get_dataset_types(self) -> None: ...
    def test_get_keys_raw(self) -> None: ...
    def test_get_default_level(self) -> None: ...
    def test_map(self) -> None: ...
    def test_query_metadata(self) -> None: ...
    def test_can_standardize(self) -> None: ...
    def test_validate(self) -> None: ...
