from . import butler_tests, camera_tests, mapper_tests
from typing import Any

class ObsTests(butler_tests.ButlerGetTests, mapper_tests.MapperTests, camera_tests.CameraTests):
    butler: Any = ...
    mapper: Any = ...
    dataIds: Any = ...
    log: Any = ...
    def setUp_tests(self, butler: Any, mapper: Any, dataIds: Any) -> None: ...
    def tearDown(self) -> None: ...
