from typing import Any

class InitialSkyWcsError(Exception): ...

def createInitialSkyWcs(visitInfo: Any, detector: Any, flipX: bool = ...): ...
def createInitialSkyWcsFromBoresight(boresight: Any, orientation: Any, detector: Any, flipX: bool = ...): ...
def bboxFromIraf(irafBBoxStr: Any): ...
