import lsst.pipe.base as pexConfig
import lsst.pipe.base as pipeBase
from typing import Any, Optional

class CoaddInputRecorderConfig(pexConfig.Config):
    saveEmptyCcds: Any = ...
    saveErrorCcds: Any = ...
    saveVisitGoodPix: Any = ...
    saveCcdWeights: Any = ...

class CoaddTempExpInputRecorder:
    task: Any = ...
    coaddInputs: Any = ...
    visitRecord: Any = ...
    def __init__(self, task: Any, visitId: Any, num: int = ...) -> None: ...
    def addCalExp(self, calExp: Any, ccdId: Any, nGoodPix: Any) -> None: ...
    def finish(self, coaddTempExp: Any, nGoodPix: Optional[Any] = ...) -> None: ...

class CoaddInputRecorderTask(pipeBase.Task):
    ConfigClass: Any = ...
    visitSchema: Any = ...
    visitGoodPixKey: Any = ...
    visitWeightKey: Any = ...
    ccdSchema: Any = ...
    ccdCcdKey: Any = ...
    ccdVisitKey: Any = ...
    ccdGoodPixKey: Any = ...
    ccdWeightKey: Any = ...
    visitFilterKey: Any = ...
    ccdFilterKey: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def makeCoaddTempExpRecorder(self, visitId: Any, num: int = ...): ...
    def makeCoaddInputs(self): ...
    def addVisitToCoadd(self, coaddInputs: Any, coaddTempExp: Any, weight: Any): ...
