from lsst.pipe.base import Struct as Struct
from typing import Any

def groupDataRefs(keys: Any, dataRefIterable: Any): ...
def groupPatchExposures(patchDataRef: Any, calexpDataRefList: Any, coaddDatasetType: str = ..., tempExpDatasetType: str = ...): ...
def getGroupDataId(groupTuple: Any, keys: Any): ...
def getGroupDataRef(butler: Any, datasetType: Any, groupTuple: Any, keys: Any): ...
