from lsst.pex.config import Config
from typing import Any

class ColortermNotFoundError(LookupError): ...

class Colorterm(Config):
    primary: Any = ...
    secondary: Any = ...
    c0: Any = ...
    c1: Any = ...
    c2: Any = ...
    def getCorrectedMagnitudes(self, refCat: Any, filterName: Any): ...
    def transformSource(self, source: Any): ...
    def transformMags(self, primary: Any, secondary: Any): ...
    def propagateFluxErrors(self, primaryFluxErr: Any, secondaryFluxErr: Any): ...

class ColortermDict(Config):
    data: Any = ...

class ColortermLibrary(Config):
    data: Any = ...
    def getColorterm(self, filterName: Any, photoCatName: Any, doRaise: bool = ...): ...
