from lsst.pipe.tasks.multiBand import DeblendCoaddSourcesTask, DetectCoaddSourcesTask, MeasureMergedCoaddSourcesTask, MergeDetectionsTask, MergeMeasurementsTask, MergeSourcesRunner
from typing import Any

class MergeDcrSourcesRunner(MergeSourcesRunner):
    @staticmethod
    def buildRefDict(parsedCmd: Any): ...
    @staticmethod
    def getTargetList(parsedCmd: Any, **kwargs: Any): ...

class DetectDcrCoaddSources(DetectCoaddSourcesTask): ...

class DeblendDcrCoaddSourcesRunner(MergeDcrSourcesRunner):
    @staticmethod
    def getTargetList(parsedCmd: Any, **kwargs: Any): ...

class DeblendDcrCoaddSourcesTask(DeblendCoaddSourcesTask):
    RunnerClass: Any = ...

class MergeDcrDetectionsTask(MergeDetectionsTask):
    RunnerClass: Any = ...

class MeasureMergedDcrCoaddSourcesTask(MeasureMergedCoaddSourcesTask): ...

class MergeDcrMeasurementsTask(MergeMeasurementsTask):
    RunnerClass: Any = ...
