import lsst.pipe.base as pexConfig
import lsst.pipe.base as pipeBase
from typing import Any

class ExampleSigmaClippedStatsConfig(pexConfig.Config):
    badMaskPlanes: Any = ...
    numSigmaClip: Any = ...
    numIter: Any = ...

class ExampleSigmaClippedStatsTask(pipeBase.Task):
    ConfigClass: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def run(self, maskedImage: Any): ...

class ExampleSimpleStatsTask(pipeBase.Task):
    ConfigClass: Any = ...
    def run(self, maskedImage: Any): ...
