import abc
import lsst.afw.image
from typing import Any

class BaseFakeSourcesConfig(lsst.pex.config.Config):
    maskPlaneName: Any = ...

class BaseFakeSourcesTask(lsst.pipe.base.Task, metaclass=abc.ABCMeta):
    ConfigClass: Any = ...
    bitmask: Any = ...
    def __init__(self, **kwargs: Any) -> None: ...
    @abc.abstractmethod
    def run(self, exposure: Any, background: Any) -> Any: ...
