import lsst.pipe.base as pipeBase
from typing import Any

class DataRefListRunner(pipeBase.TaskRunner):
    @staticmethod
    def getTargetList(parsedCmd: Any): ...
    def __call__(self, dataRefList: Any): ...

class GetRepositoryDataTask(pipeBase.CmdLineTask):
    ConfigClass: Any = ...
    RunnerClass: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def runDataRef(self, dataRefList: Any) -> None: ...
    def getIdList(self, dataRefList: Any): ...
    def getDataList(self, dataRefList: Any, datasetType: Any): ...
    def getMetadataItems(self, dataRefList: Any, datasetType: Any, nameList: Any): ...
