from .ingestCalibs import IngestCalibsConfig as IngestCalibsConfig, IngestCalibsTask as IngestCalibsTask
from .read_curated_calibs import read_all as read_all
from lsst.pipe.base import InputOnlyArgumentParser as InputOnlyArgumentParser
from typing import Any

class IngestCuratedCalibsArgumentParser(InputOnlyArgumentParser):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class IngestCuratedCalibsConfig(IngestCalibsConfig):
    def setDefaults(self) -> None: ...

class IngestCuratedCalibsTask(IngestCalibsTask):
    ArgumentParser: Any = ...
    ConfigClass: Any = ...
    def run(self, args: Any) -> None: ...
