import lsst.pipe.base as pexConfig
import lsst.pipe.base as pipeBase
from lsst.skymap import skyMapRegistry as skyMapRegistry
from typing import Any

class MakeSkyMapConfig(pexConfig.Config):
    coaddName: Any = ...
    skyMap: Any = ...
    doWrite: Any = ...

class MakeSkyMapRunner(pipeBase.TaskRunner):
    @staticmethod
    def getTargetList(parsedCmd: Any): ...
    def __call__(self, butler: Any): ...

class MakeSkyMapTask(pipeBase.CmdLineTask):
    ConfigClass: Any = ...
    RunnerClass: Any = ...
    def __init__(self, **kwargs: Any) -> None: ...
    def runDataRef(self, butler: Any): ...
    def logSkyMapInfo(self, skyMap: Any) -> None: ...
