from lsst.daf.butler.formatters.file import FileFormatter as FileFormatter
from lsst.log import Log as Log
from typing import Any

class ObjectMaskCatalog:
    table: Any = ...
    addNew: Any = ...
    def __init__(self) -> None: ...
    def __len__(self): ...
    def __iter__(self) -> Any: ...
    def __getitem__(self, i: Any): ...
    def __setitem__(self, i: Any, v: Any): ...
    @classmethod
    def readFits(cls, fileName: Any, hdu: int = ..., flags: int = ...): ...
    @staticmethod
    def read(fileName: Any): ...

def convertToAngle(var: Any, varUnit: Any, what: Any, fileName: Any, lineNo: Any): ...

class RegionFileFormatter(FileFormatter):
    extension: str = ...
