from typing import Any, Optional

class ParquetTable:
    filename: Any = ...
    def __init__(self, filename: Optional[Any] = ..., dataFrame: Optional[Any] = ...) -> None: ...
    def write(self, filename: Any) -> None: ...
    @property
    def pandasMd(self): ...
    @property
    def columnIndex(self): ...
    @property
    def columns(self): ...
    def toDataFrame(self, columns: Optional[Any] = ...): ...

class MultilevelParquetTable(ParquetTable):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def columnLevelNames(self): ...
    @property
    def columnLevels(self): ...
    def toDataFrame(self, columns: Optional[Any] = ..., droplevels: bool = ...): ...
