import lsst.afw.display as pexConf
import lsst.afw.display as pipeBase
from typing import Any, Optional

class PhotoCalConfig(pexConf.Config):
    match: Any = ...
    reserve: Any = ...
    fluxField: Any = ...
    applyColorTerms: Any = ...
    sigmaMax: Any = ...
    nSigma: Any = ...
    useMedian: Any = ...
    nIter: Any = ...
    colorterms: Any = ...
    photoCatName: Any = ...
    magErrFloor: Any = ...
    def validate(self) -> None: ...
    def setDefaults(self) -> None: ...

class PhotoCalTask(pipeBase.Task):
    ConfigClass: Any = ...
    scatterPlot: Any = ...
    fig: Any = ...
    usedKey: Any = ...
    match: Any = ...
    def __init__(self, refObjLoader: Any, schema: Optional[Any] = ..., **kwds: Any) -> None: ...
    def getSourceKeys(self, schema: Any): ...
    def extractMagArrays(self, matches: Any, filterName: Any, sourceKeys: Any): ...
    def run(self, exposure: Any, sourceCat: Any, expId: int = ...): ...
    def displaySources(self, exposure: Any, matches: Any, reserved: Any, frame: int = ...) -> None: ...
    def getZeroPoint(self, src: Any, ref: Any, srcErr: Optional[Any] = ..., zp0: Optional[Any] = ...): ...
