from lsst.pipe.base import CmdLineTask, PipelineTask, PipelineTaskConfig, PipelineTaskConnections
from typing import Any, Optional

class ProcessCcdWithFakesConnections(PipelineTaskConnections):
    exposure: Any = ...
    fakeCat: Any = ...
    wcs: Any = ...
    photoCalib: Any = ...
    icSourceCat: Any = ...
    sfdSourceCat: Any = ...
    outputExposure: Any = ...
    outputCat: Any = ...
    def __init__(self, *, config: Optional[Any] = ...) -> None: ...

class ProcessCcdWithFakesConfig(PipelineTaskConfig):
    doApplyExternalPhotoCalib: Any = ...
    externalPhotoCalibName: Any = ...
    doApplyExternalSkyWcs: Any = ...
    externalSkyWcsName: Any = ...
    coaddName: Any = ...
    srcFieldsToCopy: Any = ...
    matchRadiusPix: Any = ...
    calibrate: Any = ...
    insertFakes: Any = ...
    def setDefaults(self) -> None: ...

class ProcessCcdWithFakesTask(PipelineTask, CmdLineTask):
    ConfigClass: Any = ...
    schema: Any = ...
    def __init__(self, schema: Optional[Any] = ..., butler: Optional[Any] = ..., **kwargs: Any) -> None: ...
    def runDataRef(self, dataRef: Any): ...
    def runQuantum(self, butlerQC: Any, inputRefs: Any, outputRefs: Any) -> None: ...
    def run(self, fakeCat: Any, exposure: Any, wcs: Optional[Any] = ..., photoCalib: Optional[Any] = ..., exposureIdInfo: Optional[Any] = ..., icSourceCat: Optional[Any] = ..., sfdSourceCat: Optional[Any] = ...): ...
    calibSourceKey: Any = ...
    def copyCalibrationFields(self, calibCat: Any, sourceCat: Any, fieldsToCopy: Any): ...
