from lsst.pex.config import Config as Config, DictField as DictField, Field as Field
from lsst.pipe.base import Task as Task
from typing import Any, Optional

class PropagateVisitFlagsConfig(Config):
    flags: Any = ...
    matchRadius: Any = ...
    ccdName: Any = ...

class PropagateVisitFlagsTask(Task):
    ConfigClass: Any = ...
    schema: Any = ...
    def __init__(self, schema: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def getCcdInputs(coaddExposure: Any): ...
    def run(self, butler: Any, coaddSources: Any, ccdInputs: Any, coaddWcs: Any, visitCatalogs: Optional[Any] = ..., wcsUpdates: Optional[Any] = ...) -> None: ...
