from lsst.pex.config import Config
from lsst.pipe.base import Task
from typing import Any

class ScaleVarianceConfig(Config):
    background: Any = ...
    maskPlanes: Any = ...
    limit: Any = ...
    def setDefaults(self) -> None: ...

class ScaleVarianceTask(Task):
    ConfigClass: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def subtractedBackground(self, maskedImage: Any) -> None: ...
    def run(self, maskedImage: Any): ...
    def pixelBased(self, maskedImage: Any): ...
    def imageBased(self, maskedImage: Any): ...
