from lsst.geom import Box2D as Box2D
from lsst.pex.config import Config as Config, Field as Field, ListField as ListField
from lsst.pipe.base import Task as Task
from typing import Any, Optional

class SetPrimaryFlagsConfig(Config):
    nChildKeyName: Any = ...
    pseudoFilterList: Any = ...

class SetPrimaryFlagsTask(Task):
    ConfigClass: Any = ...
    schema: Any = ...
    isSingleFrame: Any = ...
    isPatchInnerKey: Any = ...
    isTractInnerKey: Any = ...
    isPrimaryKey: Any = ...
    def __init__(self, schema: Any, isSingleFrame: bool = ..., **kwargs: Any) -> None: ...
    def run(self, sources: Any, skyMap: Optional[Any] = ..., tractInfo: Optional[Any] = ..., patchInfo: Optional[Any] = ..., includeDeblend: bool = ...) -> None: ...
