from ..translator import MetadataTranslator
from typing import Any, Optional

class FitsTranslator(MetadataTranslator):
    @classmethod
    def can_translate(cls, header: Any, filename: Optional[Any] = ...): ...
    def to_datetime_begin(self): ...
    def to_datetime_end(self): ...
    def to_location(self): ...
