from typing import Any

def to_location_via_telescope_name(self): ...
def is_non_science(self) -> None: ...
def altitude_from_zenith_distance(zd: Any): ...
def tracking_from_degree_headers(self, radecsys: Any, radecpairs: Any, unit: Any = ...): ...
