from .suprimecam import SuprimeCamTranslator
from typing import Any, Optional

class HscTranslator(SuprimeCamTranslator):
    name: str = ...
    supported_instrument: str = ...
    default_resource_root: Any = ...
    @classmethod
    def can_translate(cls, header: Any, filename: Optional[Any] = ...): ...
    def to_exposure_id(self): ...
    def to_boresight_rotation_angle(self): ...
    def to_detector_num(self): ...
    def to_detector_exposure_id(self): ...
    def to_detector_group(self): ...
    def to_detector_unique_name(self): ...
    def to_detector_name(self): ...
