from .fits import FitsTranslator
from typing import Any

class MegaPrimeTranslator(FitsTranslator):
    name: str = ...
    supported_instrument: str = ...
    default_resource_root: Any = ...
    def to_datetime_begin(self): ...
    def to_datetime_end(self): ...
    def to_location(self): ...
    def to_detector_name(self): ...
    def to_detector_num(self): ...
    def to_observation_type(self): ...
    def to_tracking_radec(self): ...
    def to_altaz_begin(self): ...
    def to_detector_exposure_id(self): ...
    def to_pressure(self): ...
    def to_observation_counter(self): ...
