from .fits import FitsTranslator
from typing import Any, Optional

class SdssTranslator(FitsTranslator):
    name: str = ...
    supported_instrument: str = ...
    default_resource_root: Any = ...
    detector_name_id_map: Any = ...
    @classmethod
    def can_translate(cls, header: Any, filename: Optional[Any] = ...): ...
    def to_detector_unique_name(self): ...
    def to_detector_num(self): ...
    def to_observation_id(self): ...
    def to_datetime_begin(self): ...
    def to_datetime_end(self): ...
    def to_location(self): ...
    def to_observation_type(self): ...
    def to_tracking_radec(self): ...
    def to_altaz_begin(self): ...
    def to_boresight_airmass(self): ...
    def to_detector_exposure_id(self): ...
    def to_detector_group(self): ...
