from .subaru import SubaruTranslator
from typing import Any, Optional

class SuprimeCamTranslator(SubaruTranslator):
    name: str = ...
    supported_instrument: str = ...
    default_resource_root: Any = ...
    @classmethod
    def can_translate(cls, header: Any, filename: Optional[Any] = ...): ...
    def to_physical_filter(self): ...
    def to_datetime_begin(self): ...
    def to_datetime_end(self): ...
    def to_exposure_id(self): ...
    def to_visit_id(self): ...
    def to_observation_type(self): ...
    def to_tracking_radec(self): ...
    def to_altaz_begin(self): ...
    def to_boresight_rotation_angle(self): ...
    def to_detector_exposure_id(self): ...
    def to_detector_name(self): ...
