from typing import Any

def noDistort(src: Any): ...
def linearXDistort(src: Any, frac: float = ...): ...
def quadraticDistortX(src: Any, frac: float = ...): ...
def cubicDistortX(src: Any, frac: float = ...): ...
def manyTermX(src: Any, frac: float = ...): ...
def crossTerms1(src: Any, frac: float = ...): ...
def crossTerms2(src: Any, frac: float = ...): ...
def crossTerms3(src: Any, frac: float = ...): ...
def quadraticDistort(src: Any, frac: float = ...): ...
def T2DistortX(src: Any, frac: float = ...): ...
