import numpy as np
from typing import Any

class Chi2Data:
    kind: None
    raw: np.ndarray
    ndof: np.ndarray
    reduced: np.ndarray
    init_count: int = ...
    def __post_init__(self) -> None: ...
    def __init__(self, kind: Any, raw: Any, ndof: Any, reduced: Any) -> None: ...

class LogParser:
    matcher: Any = ...
    plot: Any = ...
    verbose: Any = ...
    fig: Any = ...
    section_start: Any = ...
    section_end: Any = ...
    def __init__(self, plot: bool = ..., verbose: bool = ...) -> None: ...
    def __call__(self, logfile: Any) -> None: ...

def parse_args(): ...
def main() -> None: ...
