from typing import Any, Optional

def createTwoFakeCcdImages(num1: int = ..., num2: int = ..., seed: int = ..., fakeCcdId: int = ..., photoCalibMean1: float = ..., photoCalibMean2: float = ..., fakeWcses: Any = ..., fakeVisitInfos: Any = ...): ...
def createFakeCatalog(num: Any, bbox: Any, fluxFieldName: Any, skyWcs: Optional[Any] = ..., refCat: bool = ...): ...
def getMeasuredStarsFromCatalog(catalog: Any, pixToFocal: Any): ...
