from collections import namedtuple
from typing import Any

MatchDict = namedtuple('MatchDict', ['relative', 'absolute'])

class JointcalStatistics:
    match_radius: Any = ...
    flux_limit: Any = ...
    do_photometry: Any = ...
    do_astrometry: Any = ...
    verbose: Any = ...
    log: Any = ...
    def __init__(self, match_radius: Any = ..., flux_limit: float = ..., do_photometry: bool = ..., do_astrometry: bool = ..., verbose: bool = ...) -> None: ...
    filters: Any = ...
    visits_per_dataRef: Any = ...
    new_PA1: Any = ...
    old_dist_total: Any = ...
    new_dist_total: Any = ...
    def compute_rms(self, data_refs: Any, reference: Any): ...
    def make_plots(self, data_refs: Any, old_wcs_list: Any, name: str = ..., interactive: bool = ..., per_ccd_plot: bool = ..., outdir: str = ...): ...
