from typing import Any, Optional

def dot(symb: Any, c: Any, r: Any, size: Any, ctype: Optional[Any] = ..., fontFamily: str = ..., textAngle: Optional[Any] = ...): ...
def drawLines(points: Any, ctype: Optional[Any] = ...): ...
