import abc
from lsst.daf.butler import Formatter
from typing import Any, Optional

class FileFormatter(Formatter, metaclass=abc.ABCMeta):
    extension: Optional[str] = ...
    def read(self, component: Optional[str]=...) -> Any: ...
    def fromBytes(self, serializedDataset: bytes, component: Optional[str]=...) -> Any: ...
    def write(self, inMemoryDataset: Any) -> None: ...
    def toBytes(self, inMemoryDataset: Any) -> bytes: ...
