import pandas as pd
from lsst.daf.butler import Formatter
from typing import Any, Dict, List, Optional, Union

class _ParquetLoader:
    file: Any = ...
    md: Any = ...
    columns: Any = ...
    indexLevelNames: Any = ...
    def __init__(self, path: str) -> None: ...
    def read(self, columns: Union[str, List[str], Dict[str, Union[str, List[str]]]]=...) -> pd.DataFrame: ...

class ParquetFormatter(Formatter):
    extension: str = ...
    def read(self, component: Optional[str]=...) -> Any: ...
    def write(self, inMemoryDataset: Any) -> None: ...
