from .._butlerUri import ButlerURI
from ..config import Config, ConfigSubset
from .construction import DimensionConstructionBuilder
from typing import Any, Iterable, Optional, Union

class DimensionConfig(ConfigSubset):
    requiredKeys: Any = ...
    defaultConfigFile: str = ...
    def __init__(self, other: Union[Config, ButlerURI, str, None]=..., validate: bool=..., searchPaths: Optional[Iterable[Union[str, ButlerURI]]]=...) -> None: ...
    def makeBuilder(self) -> DimensionConstructionBuilder: ...
