from ._coordinate import DataCoordinate
from ._elements import DimensionElement
from ._schema import DimensionElementFields
from typing import Any, ClassVar, Dict

class DimensionRecord:
    def __init__(self, **kwargs: Any) -> None: ...
    def __eq__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...
    def __reduce__(self) -> tuple: ...
    def toDict(self, splitTimespan: bool=...) -> Dict[str, Any]: ...
    def __getattr__(self, name: str) -> Any: ...
    dataId: DataCoordinate
    definition: ClassVar[DimensionElement]
    fields: ClassVar[DimensionElementFields]
