from .. import ddl
from ..timespan import TimespanDatabaseRepresentation
from ._elements import Dimension, DimensionElement
from typing import Any, Type

REGION_FIELD_SPEC: Any

def addDimensionForeignKey(tableSpec: ddl.TableSpec, dimension: Dimension, primaryKey: bool, *, nullable: bool=..., constraint: bool=...) -> ddl.FieldSpec: ...

class DimensionElementFields:
    element: Any = ...
    required: Any = ...
    dimensions: Any = ...
    standard: Any = ...
    implied: Any = ...
    names: Any = ...
    def __init__(self, element: DimensionElement) -> None: ...
    def makeTableSpec(self, tsRepr: Type[TimespanDatabaseRepresentation]) -> ddl.TableSpec: ...
