from typing import Any, Optional

def make_dia_object_schema(filter_names: Optional[Any] = ...): ...
def make_dia_source_schema(): ...
def make_dia_forced_source_schema(): ...
def getCcdVisitSchemaSql(): ...
