import lsst.pipe.base as pexConfig
import lsst.pipe.base as pipeBase
from typing import Any

class AssociationConfig(pexConfig.Config):
    maxDistArcSeconds: Any = ...
    diaCalculation: Any = ...
    def setDefaults(self) -> None: ...
    def validate(self) -> None: ...

class AssociationTask(pipeBase.Task):
    ConfigClass: Any = ...
    def __init__(self, **kwargs: Any) -> None: ...
    def run(self, diaSources: Any, diaObjects: Any, diaSourceHistory: Any): ...
    def check_dia_source_radec(self, dia_sources: Any): ...
    def associate_sources(self, dia_objects: Any, dia_sources: Any): ...
    def score(self, dia_objects: Any, dia_sources: Any, max_dist: Any): ...
    def match(self, dia_objects: Any, dia_sources: Any, score_struct: Any): ...
