import lsst.sphgeom as pexConfig
import lsst.sphgeom as pipeBase
from typing import Any

class LoadDiaCatalogsConfig(pexConfig.Config):
    htmLevel: Any = ...
    htmMaxRanges: Any = ...
    pixelMargin: Any = ...
    loadDiaSourcesByPixelId: Any = ...

class LoadDiaCatalogsTask(pipeBase.Task):
    ConfigClass: Any = ...
    pixelator: Any = ...
    def __init__(self, **kwargs: Any) -> None: ...
    def run(self, exposure: Any, apdb: Any): ...
    def loadDiaObjects(self, pixelRanges: Any, apdb: Any): ...
    def loadDiaSources(self, diaObjects: Any, pixelRanges: Any, dateTime: Any, apdb: Any): ...
    def loadDiaForcedSources(self, diaObjects: Any, dateTime: Any, apdb: Any): ...
