from lsst.verify.tasks import ApdbMetricConfig, ApdbMetricTask, MetadataMetricConfig, MetadataMetricTask
from typing import Any

class NumberNewDiaObjectsMetricConfig(MetadataMetricConfig):
    def setDefaults(self) -> None: ...

class NumberNewDiaObjectsMetricTask(MetadataMetricTask):
    ConfigClass: Any = ...
    def makeMeasurement(self, values: Any): ...
    @classmethod
    def getInputMetadataKeys(cls, config: Any): ...

class NumberUnassociatedDiaObjectsMetricConfig(MetadataMetricConfig):
    def setDefaults(self) -> None: ...

class NumberUnassociatedDiaObjectsMetricTask(MetadataMetricTask):
    ConfigClass: Any = ...
    def makeMeasurement(self, values: Any): ...
    @classmethod
    def getInputMetadataKeys(cls, config: Any): ...

class FractionUpdatedDiaObjectsMetricConfig(MetadataMetricConfig):
    def setDefaults(self) -> None: ...

class FractionUpdatedDiaObjectsMetricTask(MetadataMetricTask):
    ConfigClass: Any = ...
    def makeMeasurement(self, values: Any): ...
    @classmethod
    def getInputMetadataKeys(cls, config: Any): ...

class TotalUnassociatedDiaObjectsMetricConfig(ApdbMetricConfig):
    def setDefaults(self) -> None: ...

class TotalUnassociatedDiaObjectsMetricTask(ApdbMetricTask):
    ConfigClass: Any = ...
    def makeMeasurement(self, dbHandle: Any, outputDataId: Any): ...
