import lsst.pipe.base as pexConfig
import lsst.pipe.base as pipeBase
from typing import Any

class PackageAlertsConfig(pexConfig.Config):
    schemaFile: Any = ...
    minCutoutSize: Any = ...
    alertWriteLocation: Any = ...

class PackageAlertsTask(pipeBase.Task):
    ConfigClass: Any = ...
    alertSchema: Any = ...
    def __init__(self, **kwargs: Any) -> None: ...
    def run(self, diaSourceCat: Any, diaObjectCat: Any, diaSrcHistory: Any, diaForcedSources: Any, diffIm: Any, template: Any, ccdExposureIdBits: Any) -> None: ...
    def createDiaSourceBBox(self, bboxSize: Any): ...
    def createCcdDataCutout(self, cutout: Any, skyCenter: Any, photoCalib: Any): ...
    def makeLocalTransformMatrix(self, wcs: Any, center: Any, skyCenter: Any): ...
    def makeAlertDict(self, alertId: Any, diaSource: Any, diaObject: Any, objDiaSrcHistory: Any, objDiaForcedSources: Any, diffImCutout: Any, templateCutout: Any): ...
    def streamCcdDataToBytes(self, cutout: Any): ...
