from .executionGraphFixup import ExecutionGraphFixup as ExecutionGraphFixup
from lsst.pipe.base import QuantumGraph
from typing import Any, Sequence, Union

class ExecFixupDataId(ExecutionGraphFixup):
    taskLabel: Any = ...
    dimensions: Any = ...
    reverse: Any = ...
    def __init__(self, taskLabel: str, dimensions: Union[str, Sequence[str]], reverse: bool=...) -> None: ...
    def fixupQuanta(self, graph: QuantumGraph) -> QuantumGraph: ...
