from typing import Any

class PreExecInit:
    butler: Any = ...
    taskFactory: Any = ...
    skipExisting: Any = ...
    def __init__(self, butler: Any, taskFactory: Any, skipExisting: bool = ...) -> None: ...
    def initialize(self, graph: Any, saveInitOutputs: bool = ..., registerDatasetTypes: bool = ..., saveVersions: bool = ...) -> None: ...
    def initializeDatasetTypes(self, graph: Any, registerDatasetTypes: bool = ...) -> None: ...
    def saveInitOutputs(self, graph: Any) -> None: ...
    def saveConfigs(self, graph: Any) -> None: ...
    def savePackageVersions(self, graph: Any) -> None: ...
