from typing import Any, Optional

def profile(filename: Any, log: Optional[Any] = ...) -> None: ...
def printTable(rows: Any, header: Any) -> None: ...
def filterTasks(pipeline: Any, name: Any): ...
def subTaskIter(config: Any) -> None: ...
