from typing import Any

def displayReconstructedCmodel(exposure: Any, record: Any, config: Any, display: str = ...) -> None: ...
def displayReconstrucedCmodelMpl(exposure: Any, record: Any, config: Any) -> None: ...
def buildCModelImages(exposure: Any, record: Any, config: Any): ...
def reconstructCModel(exposure: Any, record: Any, config: Any): ...
