from .spatialCell import SpatialCell as SpatialCell, SpatialCellCandidateIterator as SpatialCellCandidateIterator
from lsst.pex.exceptions import NotFoundError as NotFoundError
from typing import Any

def spatialCellCandidateIter(self) -> None: ...
def spatialCellIter(self): ...
def spatialCellGetitem(self, idx: Any): ...
