import lsst.pex.config as pexConfig
from typing import Any

class PipelineTaskConfigMeta(pexConfig.ConfigMeta):
    def __new__(cls, name: Any, bases: Any, dct: Any, **kwargs: Any): ...
    def __init__(self, name: Any, bases: Any, dct: Any, **kwargs: Any) -> None: ...

class PipelineTaskConfig(pexConfig.Config, metaclass=PipelineTaskConfigMeta):
    saveMetadata: Any = ...

class ResourceConfig(pexConfig.Config):
    minMemoryMB: Any = ...
    minNumCores: Any = ...
