from typing import Any

class ConfigOverrides:
    def __init__(self) -> None: ...
    def addFileOverride(self, filename: Any) -> None: ...
    def addValueOverride(self, field: Any, value: Any) -> None: ...
    def addPythonOverride(self, python_snippet: str) -> Any: ...
    def addInstrumentOverride(self, instrument: str, task_name: str) -> Any: ...
    def applyTo(self, config: Any) -> None: ...
