from typing import Any, Optional

class MissingTaskFactoryError(Exception): ...
class DuplicateOutputError(Exception): ...
class PipelineDataCycleError(Exception): ...

def isPipelineOrdered(pipeline: Any, taskFactory: Optional[Any] = ...): ...
def orderPipeline(pipeline: Any): ...
