from .butlerQuantumContext import ButlerQuantumContext
from .connections import InputQuantizedConnection, OutputQuantizedConnection
from .task import Task
from typing import Any, Optional

class PipelineTask(Task):
    canMultiprocess: bool = ...
    def __init__(self, *, config: Optional[Any] = ..., log: Optional[Any] = ..., initInputs: Optional[Any] = ..., **kwargs: Any) -> None: ...
    def run(self, **kwargs: Any) -> None: ...
    def runQuantum(self, butlerQC: ButlerQuantumContext, inputRefs: InputQuantizedConnection, outputRefs: OutputQuantizedConnection) -> Any: ...
    def getResourceConfig(self): ...
