from typing import Any

class Struct:
    def __init__(self, **keyArgs: Any) -> None: ...
    def getDict(self): ...
    def mergeItems(self, struct: Any, *nameList: Any) -> None: ...
    def copy(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __len__(self): ...
