from typing import Any

def makeQuantum(task: Any, butler: Any, dataId: Any, ioDataIds: Any): ...
def runTestQuantum(task: Any, butler: Any, quantum: Any, mockRun: bool = ...): ...
def assertValidOutput(task: Any, result: Any) -> None: ...
