from .apCorrMap import ApCorrMap as ApCorrMap
from lsst.utils import continueClass as continueClass
from typing import Any

class ApCorrMap:
    def keys(self) -> None: ...
    def values(self) -> None: ...
    __iter__: Any = ...
