from lsst.daf.butler.cli.butler import LoaderCLI as LoaderCLI
from lsst.daf.butler.cli.opt import log_level_option as log_level_option, long_log_option as long_log_option
from typing import Any

class PipetaskCLI(LoaderCLI):
    localCmdPkg: str = ...

def cli(log_level: Any, long_log: Any) -> None: ...
def main(): ...
