from lsst.verify.tasks import MetadataMetricConfig, MetadataMetricTask
from typing import Any

class TimeMethodMetricConfig(MetadataMetricConfig):
    target: Any = ...
    metric: Any = ...
    def validate(self) -> None: ...
TimingMetricConfig = TimeMethodMetricConfig

class TimingMetricTask(MetadataMetricTask):
    ConfigClass: Any = ...
    @classmethod
    def getInputMetadataKeys(cls, config: Any): ...
    def makeMeasurement(self, timings: Any): ...
MemoryMetricConfig = TimeMethodMetricConfig

class MemoryMetricTask(MetadataMetricTask):
    ConfigClass: Any = ...
    @classmethod
    def getInputMetadataKeys(cls, config: Any): ...
    def makeMeasurement(self, memory: Any): ...
