import abc
import lsst.verify.gen2tasks.testUtils as gen2Utils
import lsst.verify.gen2tasks.testUtils
from typing import Any

class MetricTaskTestCase(lsst.utils.tests.TestCase, metaclass=abc.ABCMeta):
    @classmethod
    @abc.abstractmethod
    def makeTask(cls) -> Any: ...
    task: Any = ...
    taskClass: Any = ...
    def setUp(self) -> None: ...
    def testOutputDatasetName(self) -> None: ...
    def testConfigValidation(self) -> None: ...

class MetadataMetricTestCase(gen2Utils.MetricTaskTestCase, MetricTaskTestCase, metaclass=abc.ABCMeta):
    def testValidRun(self) -> None: ...
    def testAmbiguousRun(self) -> None: ...
    def testPassThroughRun(self) -> None: ...
    def testDimensionsOverride(self) -> None: ...

class ApdbMetricTestCase(gen2Utils.MetricTaskTestCase, MetricTaskTestCase, metaclass=abc.ABCMeta):
    @classmethod
    def makeDbInfo(cls): ...
    def testValidRun(self) -> None: ...
    def testDataIdRun(self) -> None: ...
    def testPassThroughRun(self) -> None: ...
