import abc
from ..jsonmixin import JsonSerializationMixin
from typing import Any

class Specification(JsonSerializationMixin, metaclass=abc.ABCMeta):
    def __init__(self, name: Any, **kwargs: Any) -> None: ...
    @property
    def name(self): ...
    @property
    def metric_name(self): ...
    @property
    def tags(self): ...
    @tags.setter
    def tags(self, t: Any) -> None: ...
    @property
    @abc.abstractmethod
    def type(self) -> Any: ...
    @property
    def json(self): ...
    @abc.abstractmethod
    def check(self, measurement: Any) -> Any: ...
    def query_metadata(self, metadata: Any, arg_driven: bool = ...): ...
