import lsst.pipe.base as pexConfig
import lsst.pipe.base as pipeBase
from typing import Any

class AssembleCcdConfig(pexConfig.Config):
    doTrim: Any = ...
    keysToRemove: Any = ...

class AssembleCcdTask(pipeBase.Task):
    ConfigClass: Any = ...
    allKeysToRemove: Any = ...
    def __init__(self, **kwargs: Any) -> None: ...
    def assembleCcd(self, assembleInput: Any): ...
    def postprocessExposure(self, outExposure: Any, inExposure: Any) -> None: ...
    def setWcs(self, outExposure: Any, inExposure: Any) -> None: ...
