from lsst.pex.config import Config as Config, Field as Field
from lsst.pipe.base import Task as Task
from typing import Any

class VignetteConfig(Config):
    xCenter: Any = ...
    yCenter: Any = ...
    radius: Any = ...
    numPolygonPoints: Any = ...
    doWriteVignettePolygon: Any = ...

class VignetteTask(Task):
    ConfigClass: Any = ...
    def run(self, exposure: Any): ...
