import lsst.pipe.base as pipeBase
from typing import Any

class CoaddDataIdContainer(pipeBase.DataIdContainer):
    def getSkymap(self, namespace: Any): ...
    def makeDataRefList(self, namespace: Any) -> None: ...

class ExistingCoaddDataIdContainer(CoaddDataIdContainer):
    refList: Any = ...
    def makeDataRefList(self, namespace: Any) -> None: ...
