from ..util import averageDecFromCat as averageDecFromCat, averageRaFromCat as averageRaFromCat, sphDist as sphDist
from lsst.verify import Datum as Datum, Measurement as Measurement
from typing import Any, Optional

def measureAMx(metric: Any, matchedDataset: Any, D: Any, width: float = ..., magRange: Optional[Any] = ..., verbose: bool = ...): ...
def calcRmsDistances(groupView: Any, annulus: Any, magRange: Any, verbose: bool = ...): ...
def matchVisitComputeDistance(visit_obj1: Any, ra_obj1: Any, dec_obj1: Any, visit_obj2: Any, ra_obj2: Any, dec_obj2: Any): ...
def radiansToMilliarcsec(rad: Any): ...
def arcminToRadians(arcmin: Any): ...
