from ..util import averageDecFromCat as averageDecFromCat, averageRaFromCat as averageRaFromCat, medianEllipticity1ResidualsFromCat as medianEllipticity1ResidualsFromCat, medianEllipticity2ResidualsFromCat as medianEllipticity2ResidualsFromCat
from lsst.verify import Datum as Datum, Measurement as Measurement, ThresholdSpecification as ThresholdSpecification
from typing import Any

def measureTEx(metric: Any, matchedDataset: Any, D: Any, bin_range_operator: Any, verbose: bool = ...): ...
def correlation_function_ellipticity_from_matches(matches: Any, **kwargs: Any): ...
def correlation_function_ellipticity(ra: Any, dec: Any, e1_res: Any, e2_res: Any, nbins: int = ..., min_sep: float = ..., max_sep: int = ..., sep_units: str = ..., verbose: bool = ...): ...
def select_bin_from_corr(r: Any, xip: Any, xip_err: Any, radius: Any = ..., operator: Any = ...): ...
def plot_correlation_function_ellipticity(r: Any, xip: Any, xip_err: Any, plotfile: str = ...) -> None: ...
