import abc
import click
from .cliLog import CliLog as CliLog
from .opt import log_level_option as log_level_option, long_log_option as long_log_option
from lsst.utils import doImport as doImport
from typing import Any

log: Any

class LoaderCLI(click.MultiCommand, abc.ABC, metaclass=abc.ABCMeta):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    @abc.abstractmethod
    def localCmdPkg(self) -> Any: ...
    def getLocalCommands(self): ...
    def list_commands(self, ctx: Any): ...
    def get_command(self, ctx: Any, name: Any): ...
    @classmethod
    def getPluginList(cls): ...

class ButlerCLI(LoaderCLI):
    localCmdPkg: str = ...
    pluginEnvVar: str = ...

def cli(log_level: Any, long_log: Any) -> None: ...
def main(): ...
