from typing import Any

class CliLog:
    defaultLsstLogLevel: Any = ...
    lsstLog_longLogFmt: str = ...
    lsstLog_normalLogFmt: str = ...
    pylog_longLogFmt: str = ...
    pylog_longLogDateFmt: str = ...
    pylog_normalFmt: str = ...
    configState: Any = ...
    @classmethod
    def initLog(cls, longlog: Any) -> None: ...
    @classmethod
    def getHandlerId(cls): ...
    @classmethod
    def resetLog(cls) -> None: ...
    @classmethod
    def setLogLevels(cls, logLevels: Any) -> None: ...
    class ComponentSettings:
        component: Any = ...
        pythonLogLevel: Any = ...
        lsstLogLevel: Any = ...
        def __init__(self, component: Any) -> None: ...
    @classmethod
    def replayConfigState(cls, configState: Any) -> None: ...
