from ._table import AliasMap as AliasMap
from lsst.utils import continueClass as continueClass
from typing import Any

class AliasMap:
    def keys(self) -> None: ...
    def values(self) -> None: ...
    def __iter__(self) -> Any: ...
