from lsst.utils import TemplateMeta
from typing import Any, Optional

class BaseRecord:
    def extract(self, *patterns: Any, **kwargs: Any): ...

class Catalog(metaclass=TemplateMeta):
    def getColumnView(self): ...
    columns: Any = ...
    def __getitem__(self, key: Any): ...
    def __setitem__(self, key: Any, value: Any): ...
    def __delitem__(self, key: Any) -> None: ...
    def append(self, record: Any) -> None: ...
    def insert(self, key: Any, value: Any) -> None: ...
    def clear(self) -> None: ...
    def addNew(self): ...
    def cast(self, type_: Any, deep: bool = ...): ...
    def copy(self, deep: bool = ...): ...
    def extend(self, iterable: Any, deep: bool = ..., mapper: Optional[Any] = ...) -> None: ...
    def __reduce__(self): ...
    def asAstropy(self, cls: Optional[Any] = ..., copy: bool = ..., unviewable: str = ...): ...
    def __dir__(self): ...
    def __getattr__(self, name: Any): ...
