from ._table import KeyFlag as KeyFlag
from lsst.utils import continueClass as continueClass
from typing import Any, Optional

class _BaseColumnViewBase:
    def getBits(self, keys: Optional[Any] = ...): ...
    def __getitem__(self, key: Any): ...
    get: Any = ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    set: Any = ...
    def get_bool_array(self, key: Any): ...
    def extract(self, *patterns: Any, **kwds: Any): ...
