from lsst.utils import TemplateMeta
from typing import Any, Optional

class Key(metaclass=TemplateMeta): ...
class Field(metaclass=TemplateMeta): ...
class SchemaItem(metaclass=TemplateMeta): ...

class Schema:
    def getOrderedNames(self): ...
    def __iter__(self) -> Any: ...
    def checkUnits(self, parse_strict: str = ...) -> None: ...
    def addField(self, field: Any, type: Optional[Any] = ..., doc: str = ..., units: str = ..., size: Optional[Any] = ..., doReplace: bool = ..., parse_strict: str = ...): ...
    def extract(self, *patterns: Any, **kwargs: Any): ...
    def __reduce__(self): ...
