from typing import Any, Optional

def makeMergedSchema(sourceSchema: Any, targetSchema: Any, sourcePrefix: Optional[Any] = ..., targetPrefix: Optional[Any] = ...): ...
def copyIntoCatalog(catalog: Any, target: Any, sourceSchema: Optional[Any] = ..., sourcePrefix: Optional[Any] = ..., targetPrefix: Optional[Any] = ...) -> None: ...
def matchesToCatalog(matches: Any, matchMeta: Any): ...
def matchesFromCatalog(catalog: Any, sourceSlotConfig: Optional[Any] = ...): ...
def copyAliasMapWithPrefix(inSchema: Any, outSchema: Any, prefix: str = ...): ...
