from typing import Any

def joinWords(items: Any): ...
def diffSchemas(schema1: Any, schema2: Any, flags: Any = ...): ...
def assertSchemasEqual(testCase: Any, schema1: Any, schema2: Any, flags: Any = ...) -> None: ...
