from typing import Any

class OptionGroup:
    def __call__(self, f: Any): ...

class pipeline_build_options(OptionGroup):
    decorators: Any = ...
    def __init__(self) -> None: ...

class qgraph_options(OptionGroup):
    decorators: Any = ...
    def __init__(self) -> None: ...

class butler_options(OptionGroup):
    decorators: Any = ...
    def __init__(self) -> None: ...

class execution_options(OptionGroup):
    decorators: Any = ...
    def __init__(self) -> None: ...

class meta_info_options(OptionGroup):
    decorators: Any = ...
    def __init__(self) -> None: ...
