from lsst.daf.butler.registry.interfaces import DatasetIdRef, DatastoreRegistryBridge
from typing import Iterable, Iterator

class EphemeralDatastoreRegistryBridge(DatastoreRegistryBridge):
    def __init__(self, datastoreName: str) -> None: ...
    def insert(self, refs: Iterable[DatasetIdRef]) -> None: ...
    def moveToTrash(self, refs: Iterable[DatasetIdRef]) -> None: ...
    def check(self, refs: Iterable[DatasetIdRef]) -> Iterable[DatasetIdRef]: ...
    def __contains__(self, ref: DatasetIdRef) -> bool: ...
    def emptyTrash(self) -> Iterator[Iterable[DatasetIdRef]]: ...
