from lsst.obs.base import CameraMapper
from typing import Any

class BaseMapper(CameraMapper):
    packageName: str = ...
    policy: Any = ...
    def __init__(self, root: Any) -> None: ...
    @classmethod
    def getPackageDir(cls): ...
