from typing import Any

class CRPixelPrinter:
    val: Any = ...
    def __init__(self, val: Any) -> None: ...
    def to_string(self): ...

printers: Any

def register(obj: Any) -> None: ...
def build_meas_algorithms_dictionary(): ...
