from typing import Any

class RawAndFlatContainer:
    raw: Any = ...
    flat: Any = ...
    def __init__(self, a: Any, b: Any) -> None: ...

def RawAndFlatAssembler(dataId: Any, componentInfo: Any, cls: Any): ...
def RawAndFlatDisassembler(obj: Any, dataId: Any, componentInfo: Any) -> None: ...
