from lsst.obs.base import MakeRawVisitInfo
from typing import Any

class MakeTestRawVisitInfo(MakeRawVisitInfo):
    observatory: Any = ...
    def setArgDict(self, md: Any, argDict: Any): ...
    def getDateAvg(self, md: Any, exposureTime: Any): ...
