import lsst.daf.persistence
from lsst.obs.base import CameraMapper
from typing import Any, Optional

class TestMapper(CameraMapper):
    packageName: str = ...
    MakeRawVisitInfoClass: Any = ...
    doFootprints: bool = ...
    filterIdMap: Any = ...
    def __init__(self, inputPolicy: Optional[Any] = ..., **kwargs: Any) -> None: ...
    def bypass_ccdExposureId(self, datasetType: Any, pythonType: Any, location: Any, dataId: Any): ...
    def bypass_ccdExposureId_bits(self, datasetType: Any, pythonType: Any, location: Any, dataId: Any): ...
    def validate(self, dataId: Any): ...

class MapperForTestCalexpMetadataObjects(lsst.obs.base.CameraMapper):
    packageName: str = ...
    filterIdMap: Any = ...
    def __init__(self, root: Any, parentRegistry: Optional[Any] = ..., repositoryCfg: Optional[Any] = ...) -> None: ...
