from lsst.utils import TemplateMeta
from typing import Any, Optional

class GenericMap(metaclass=TemplateMeta):
    def __eq__(self, other: Any) -> Any: ...
    keys: Any = ...
    values: Any = ...
    items: Any = ...

class MutableGenericMap(GenericMap):
    setdefault: Any = ...
    update: Any = ...
    def pop(self, key: Any, default: Optional[Any] = ...): ...

class AutoKeyMeta(TemplateMeta):
    def __call__(cls, *args: Any, **kwargs: Any): ...
