from typing import Any

class NoMapperException(Exception): ...

class NoResults(RuntimeError):
    def __init__(self, message: Any, datasetType: Any, dataId: Any) -> None: ...

class MultipleResults(RuntimeError):
    locations: Any = ...
    def __init__(self, message: Any, datasetType: Any, dataId: Any, locations: Any) -> None: ...

class ParentsMismatch(RuntimeError):
    def __init__(self, message: Any) -> None: ...
