from . import Policy as Policy
from typing import Any

class Mapper:
    @staticmethod
    def Mapper(cfg: Any): ...
    def __new__(cls, *args: Any, **kwargs: Any): ...
    def __init__(self, **kwargs: Any) -> None: ...
    def keys(self) -> None: ...
    def queryMetadata(self, datasetType: Any, format: Any, dataId: Any): ...
    def getDatasetTypes(self): ...
    def map(self, datasetType: Any, dataId: Any, write: bool = ...): ...
    def canStandardize(self, datasetType: Any): ...
    def standardize(self, datasetType: Any, item: Any, dataId: Any): ...
    def validate(self, dataId: Any): ...
    def backup(self, datasetType: Any, dataId: Any) -> None: ...
    def getRegistry(self) -> None: ...
