from lsst.daf.persistence import ButlerLocation as ButlerLocation, Mapper as Mapper, Policy as Policy
from typing import Any

class RepositoryMapper(Mapper):
    policy: Any = ...
    storage: Any = ...
    def __init__(self, storage: Any, policy: Any) -> None: ...
    def map_cfg(self, dataId: Any, write: Any): ...
    def map_repo(self, dataId: Any, write: Any): ...
