from . import NoRepositroyAtRoot as NoRepositroyAtRoot
from typing import Any

class Storage:
    storages: Any = ...
    repositoryCfgs: Any = ...
    def __init__(self) -> None: ...
    @staticmethod
    def registerStorageClass(scheme: Any, cls: Any) -> None: ...
    def getRepositoryCfg(self, uri: Any): ...
    @staticmethod
    def putRepositoryCfg(cfg: Any, uri: Any): ...
    @staticmethod
    def getMapperClass(uri: Any): ...
    @staticmethod
    def makeFromURI(uri: Any, create: bool = ...): ...
    @staticmethod
    def isPosix(uri: Any): ...
    @staticmethod
    def relativePath(fromUri: Any, toUri: Any): ...
    @staticmethod
    def absolutePath(fromUri: Any, toUri: Any): ...
    @staticmethod
    def search(uri: Any, path: Any): ...
    @staticmethod
    def storageExists(uri: Any): ...
