from enum import Enum
from typing import Any, Optional

class WhenToSaveQuantumGraphs(Enum):
    QGRAPH: int = ...
    TRANSFORM: int = ...
    PREPARE: int = ...
    SUBMIT: int = ...

def chdir(path: Any) -> None: ...
def create_job_quantum_graph_filename(job: Any, out_prefix: Optional[Any] = ...): ...
def save_qg_subgraph(qgraph: Any, out_filename: Any) -> None: ...
