import networkx
from lsst.pipe.base import QuantumGraph as QuantumGraph
from typing import Any, Optional

class ClusteredQuantumGraph(networkx.DiGraph):
    def add_cluster(self, name: Any, qgraph: Any, label: Optional[Any] = ...) -> None: ...
    def add_node(self, node_for_adding: Any, **attr: Any) -> None: ...
    def add_nodes_from(self, nodes_for_adding: Any, **attr: Any) -> None: ...
