from lsst.daf.butler import DimensionUniverse as DimensionUniverse
from lsst.pipe.base.graph import QuantumGraph as QuantumGraph
from lsst.utils import doImport as doImport
from typing import Any, Optional

def pre_transform(config: Any, out_prefix: Optional[Any] = ...): ...
def execute(command: Any, filename: Any): ...
def create_quantum_graph(config: Any, out_prefix: Optional[Any] = ...): ...
def read_quantum_graph(qgraph_filename: Any): ...
def cluster_quanta(config: Any, qgraph: Any, name: Any): ...
