from .wms_service import WmsStates as WmsStates
from typing import Any

SUMMARY_FMT: str

def print_headers() -> None: ...
def print_run(run_report: Any) -> None: ...
def group_jobs_by_state(jobs: Any): ...
def group_jobs_by_label(jobs: Any): ...
def print_single_run_summary(run_report: Any) -> None: ...
