import lsst.pex.config as pexConfig
from .subtractBackground import SubtractBackgroundTask as SubtractBackgroundTask
from typing import Any

class FindCosmicRaysConfig(pexConfig.Config):
    nCrPixelMax: Any = ...
    minSigma: Any = ...
    min_DN: Any = ...
    cond3_fac: Any = ...
    cond3_fac2: Any = ...
    niteration: Any = ...
    keepCRs: Any = ...
    background: Any = ...
    def setDefaults(self) -> None: ...
