from lsst.pex.config import Config
from typing import Any, Optional

SigmaPerFwhm: Any

class GaussianPsfFactory(Config):
    size: Any = ...
    sizeFactor: Any = ...
    minSize: Any = ...
    maxSize: Any = ...
    defaultFwhm: Any = ...
    addWing: Any = ...
    wingFwhmFactor: Any = ...
    wingAmplitude: Any = ...
    def computeSizeAndSigma(self, fwhm: Optional[Any] = ...): ...
    def validate(self) -> None: ...
    def apply(self, fwhm: Optional[Any] = ...): ...
    @classmethod
    def makeField(cls, doc: Any): ...
