from typing import Any

class HtmIndexer:
    htm: Any = ...
    def __init__(self, depth: int = ...) -> None: ...
    def getShardIds(self, ctrCoord: Any, radius: Any): ...
    def indexPoints(self, raList: Any, decList: Any): ...
    @staticmethod
    def makeDataId(shardId: Any, datasetName: Any): ...
