from typing import Any

class IngestIndexManager:
    filenames: Any = ...
    config: Any = ...
    file_reader: Any = ...
    indexer: Any = ...
    schema: Any = ...
    key_map: Any = ...
    htmRange: Any = ...
    addRefCatMetadata: Any = ...
    log: Any = ...
    coord_err_unit: Any = ...
    def __init__(self, filenames: Any, config: Any, file_reader: Any, indexer: Any, schema: Any, key_map: Any, htmRange: Any, addRefCatMetadata: Any, log: Any) -> None: ...
    nInputFiles: Any = ...
    def run(self, inputFiles: Any) -> None: ...
    def getCatalog(self, pixelId: Any, schema: Any, nNewElements: Any): ...
    @staticmethod
    def computeCoord(row: Any, ra_name: Any, dec_name: Any): ...

class IngestGaiaManager(IngestIndexManager): ...
