import lsst.pipe.base as pexConfig
import lsst.pipe.base as pipeBase
from typing import Any

class InstallGaussianPsfConfig(pexConfig.Config):
    fwhm: Any = ...
    width: Any = ...
    def validate(self) -> None: ...

class InstallGaussianPsfTask(pipeBase.Task):
    ConfigClass: Any = ...
    def run(self, exposure: Any) -> None: ...
