import lsst.pex.config
from lsst.pipe.base import Task
from typing import Any

class FluxKeys:
    flux: Any = ...
    err: Any = ...
    flag: Any = ...
    used: Any = ...
    def __init__(self, name: Any, schema: Any) -> None: ...

class MeasureApCorrConfig(lsst.pex.config.Config):
    refFluxName: Any = ...
    sourceSelector: Any = ...
    minDegreesOfFreedom: Any = ...
    fitConfig: Any = ...
    numIter: Any = ...
    numSigmaClip: Any = ...
    allowFailure: Any = ...
    def validate(self) -> None: ...

class MeasureApCorrTask(Task):
    ConfigClass: Any = ...
    refFluxKeys: Any = ...
    toCorrect: Any = ...
    def __init__(self, schema: Any, **kwds: Any) -> None: ...
    def run(self, exposure: Any, catalog: Any): ...
