import abc
import lsst.pex.config as pexConfig
import lsst.pex.config as pipeBase
from typing import Any, Optional

class BasePsfDeterminerConfig(pexConfig.Config):
    kernelSize: Any = ...
    kernelSizeMin: Any = ...
    kernelSizeMax: Any = ...

class BasePsfDeterminerTask(pipeBase.Task, metaclass=abc.ABCMeta):
    usesMatches: bool = ...
    ConfigClass: Any = ...
    def __init__(self, config: Any, schema: Optional[Any] = ..., **kwds: Any) -> None: ...
    @abc.abstractmethod
    def determinePsf(self, exposure: Any, psfCandidateList: Any, metadata: Optional[Any] = ...) -> Any: ...

psfDeterminerRegistry: Any
