from lsst.pex.config import Config
from lsst.pipe.base import Task
from typing import Any, Optional

class ReserveSourcesConfig(Config):
    fraction: Any = ...
    seed: Any = ...

class ReserveSourcesTask(Task):
    ConfigClass: Any = ...
    columnName: Any = ...
    key: Any = ...
    def __init__(self, columnName: Optional[Any] = ..., schema: Optional[Any] = ..., doc: Optional[Any] = ..., **kwargs: Any) -> None: ...
    def run(self, sources: Any, prior: Optional[Any] = ..., expId: int = ...): ...
    def select(self, numSources: Any, expId: int = ...): ...
    def applySelectionPrior(self, prior: Any, selection: Any): ...
    def markSources(self, sources: Any, selection: Any) -> None: ...
