from lsst.pex.config import Config
from lsst.pipe.base import Task
from typing import Any

class SkyObjectsConfig(Config):
    avoidMask: Any = ...
    growMask: Any = ...
    sourceRadius: Any = ...
    nSources: Any = ...
    nTrialSources: Any = ...
    nTrialSourcesMultiplier: Any = ...

def generateSkyObjects(mask: Any, seed: Any, config: Any): ...

class SkyObjectsTask(Task):
    ConfigClass: Any = ...
    def run(self, mask: Any, seed: Any): ...
