import abc
import lsst.pipe.base as pexConfig
import lsst.pipe.base as pipeBase
from typing import Any, Optional

class BaseStarSelectorConfig(pexConfig.Config):
    badFlags: Any = ...

class BaseStarSelectorTask(pipeBase.Task, metaclass=abc.ABCMeta):
    usesMatches: bool = ...
    ConfigClass: Any = ...
    def __init__(self, schema: Any, **kwds: Any) -> None: ...
    def run(self, exposure: Any, sourceCat: Any, matches: Optional[Any] = ..., isStarField: Optional[Any] = ...): ...
    @abc.abstractmethod
    def selectStars(self, exposure: Any, sourceCat: Any, matches: Optional[Any] = ...) -> Any: ...

starSelectorRegistry: Any
