from . import Defect as Defect, SingleGaussianPsf as SingleGaussianPsf
from typing import Any

def plantSources(bbox: Any, kwid: Any, sky: Any, coordList: Any, addPoissonNoise: bool = ...): ...
def makeRandomTransmissionCurve(rng: Any, minWavelength: float = ..., maxWavelength: float = ..., nWavelengths: int = ..., maxRadius: float = ..., nRadii: int = ..., perturb: float = ...): ...
def makeDefectList(): ...
