import lsst.log as virtualDevice
from .footprints import createFootprintsTable as createFootprintsTable
from typing import Any, Optional

class FireflyError(Exception):
    def __init__(self, str: Any) -> None: ...

def firefly_version(): ...

class DisplayImpl(virtualDevice.DisplayImpl):
    def __init__(self, display: Any, verbose: bool = ..., url: Optional[Any] = ..., name: Optional[Any] = ..., *args: Any, **kwargs: Any) -> None: ...
    def getClient(self): ...
    def clearViewer(self) -> None: ...
    def resetLayout(self) -> None: ...
    def overlayFootprints(self, catalog: Any, color: str = ..., highlightColor: str = ..., selectColor: str = ..., style: str = ..., layerString: str = ..., titleString: str = ...) -> None: ...
