from typing import Any

def imageReadFitsWithOptions(cls, source: Any, options: Any): ...
def imageWriteFitsWithOptions(self, dest: Any, options: Any) -> None: ...
def exposureWriteFitsWithOptions(self, dest: Any, options: Any) -> None: ...
