from lsst.utils import TemplateMeta
from typing import Any

MaskPixel: Any

class Mask(metaclass=TemplateMeta):
    TEMPLATE_PARAMS: Any = ...
    TEMPLATE_DEFAULTS: Any = ...
    def __reduce__(self): ...
    readFitsWithOptions: Any = ...
    writeFitsWithOptions: Any = ...
