from . import TestObject as TestObject
from .. import ButlerLocation as ButlerLocation, Mapper as Mapper, Storage as Storage
from typing import Any, Optional

class EmptyTestMapper(Mapper):
    root: Any = ...
    kwargs: Any = ...
    def __init__(self, root: Optional[Any] = ..., parentRegistry: Optional[Any] = ..., repositoryCfg: Optional[Any] = ..., **kwargs: Any) -> None: ...

class MapperForTestWriting(Mapper):
    root: Any = ...
    storage: Any = ...
    def __init__(self, root: Any, **kwargs: Any) -> None: ...
    def map_foo(self, dataId: Any, write: Any): ...
