from typing import Any

class Info:
    def __init__(self, modname: Any) -> None: ...
    def __getattr__(self, what: Any): ...
    def __setattr__(self, what: Any, value: Any) -> None: ...
getInfo = Info

def getDebugFrame(debugDisplay: Any, name: Any): ...
