from lsst.ctrl.pool.parallel import BatchPoolTask
from typing import Any, Optional

class DemoTask(BatchPoolTask):
    ConfigClass: Any = ...
    @classmethod
    def batchWallTime(cls, time: Any, parsedCmd: Any, numCores: Any): ...
    def runDataRef(self, visitRef: Any) -> None: ...
    def run(self, cache: Any, dataId: Any, butler: Optional[Any] = ...): ...
