from typing import Any

def astromErrModel(snr: Any, theta: int = ..., sigmaSys: int = ..., C: int = ...): ...
def fitAstromErrModel(snr: Any, dist: Any): ...
def build_astrometric_error_model(matchedMultiVisitDataset: Any, selection: Any, medianRef: int = ..., matchRef: int = ...): ...
