from lsst.pex.config import Config
from lsst.pipe.base import CmdLineTask, TaskRunner
from typing import Any

class MatchedVisitMetricsRunner(TaskRunner):
    @staticmethod
    def getTargetList(parsedCmd: Any, **kwargs: Any): ...
    def __call__(self, args: Any): ...

class MatchedVisitMetricsConfig(Config):
    instrumentName: Any = ...
    datasetName: Any = ...
    outputPrefix: Any = ...
    metricsRepository: Any = ...
    brightSnrMin: Any = ...
    brightSnrMax: Any = ...
    makeJson: Any = ...
    makePlots: Any = ...
    matchRadius: Any = ...
    doApplyExternalPhotoCalib: Any = ...
    externalPhotoCalibName: Any = ...
    doApplyExternalSkyWcs: Any = ...
    externalSkyWcsName: Any = ...
    skipTEx: Any = ...
    verbose: Any = ...

class MatchedVisitMetricsTask(CmdLineTask):
    ConfigClass: Any = ...
    RunnerClass: Any = ...
    def run(self, butler: Any, filterName: Any, output: Any, dataIds: Any) -> None: ...
