from typing import Any

def photErrModel(mag: Any, sigmaSys: Any, gamma: Any, m5: Any): ...
def fitPhotErrModel(mag: Any, mag_err: Any): ...
def build_photometric_error_model(matchedMultiVisitDataset: Any, selection: Any, medianRef: int = ..., matchRef: int = ...): ...
