from typing import Any

def ellipticity_from_cat(cat: Any, slot_shape: str = ...): ...
def ellipticity_from_shape(shape: Any): ...
def ellipticity(i_xx: Any, i_xy: Any, i_yy: Any): ...
def averageRaDec(ra: Any, dec: Any): ...
def averageRaDecFromCat(cat: Any): ...
def positionRms(ra_mean: Any, dec_mean: Any, ra: Any, dec: Any): ...
def positionRmsFromCat(cat: Any): ...
def sphDist(ra_mean: Any, dec_mean: Any, ra: Any, dec: Any): ...
def averageRaFromCat(cat: Any): ...
def averageDecFromCat(cat: Any): ...
def medianEllipticityResidualsFromCat(cat: Any): ...
def medianEllipticity1ResidualsFromCat(cat: Any): ...
def medianEllipticity2ResidualsFromCat(cat: Any): ...
def getCcdKeyName(dataId: Any): ...
def raftSensorToInt(visitId: Any): ...
def repoNameToPrefix(repo: Any): ...
def discoverDataIds(repo: Any, **kwargs: Any): ...
def loadParameters(configFile: Any): ...
def loadDataIdsAndParameters(configFile: Any): ...
def constructDataIds(filters: Any, visits: Any, ccds: Any, ccdKeyName: str = ...): ...
def loadRunList(configFile: Any): ...
def constructRunList(visits: Any, ccds: Any, ccdKeyName: str = ...): ...
