from typing import Any

class IndexGenerator:
    order: Any = ...
    size: Any = ...
    def __init__(self, order: Any) -> None: ...
    @staticmethod
    def make(self, order: Any, basisType: Any): ...
    def __len__(self): ...

class HermiteIndexGenerator(IndexGenerator):
    def __iter__(self) -> Any: ...

class LaguerreIndexGenerator(IndexGenerator):
    def __iter__(self) -> Any: ...
