from collections import namedtuple
from typing import Any

ManifestItem = namedtuple('ManifestItem', ['name', 'git_sha', 'version', 'dependencies'])

class Manifest:
    def __init__(self, manifest_stream: Any) -> None: ...
    def __iter__(self) -> Any: ...
    def items(self) -> None: ...
    def __len__(self): ...
    def __getitem__(self, package_name: Any): ...
    def __contains__(self, package_name: Any): ...
    @property
    def build(self): ...
