from typing import Any

class LsstswRepos:
    def __init__(self, dirname: Any) -> None: ...
    def __contains__(self, package_name: Any): ...
    def __len__(self): ...
    @property
    def manifest_path(self): ...
    def get_package_repo_path(self, package_name: Any): ...
    def get_package_branch(self, package_name: Any): ...
    def get_package_commit_sha(self, package_name: Any): ...
    def get_package_repo_url(self, package_name: Any): ...
