import argparse
from typing import Any, Optional

class _InputOutputParser(argparse.ArgumentParser):
    def __init__(self) -> None: ...

class _ProcessingParser(argparse.ArgumentParser):
    def __init__(self) -> None: ...

class _ApVerifyParser(argparse.ArgumentParser):
    def __init__(self) -> None: ...

class _IngestOnlyParser(argparse.ArgumentParser):
    def __init__(self) -> None: ...

class _FormattedType:
    def __init__(self, fmt: Any, msg: str = ...) -> None: ...
    def __call__(self, value: Any): ...

class _DatasetAction(argparse.Action):
    def __call__(self, _parser: Any, namespace: Any, values: Any, _option_string: Optional[Any] = ...) -> None: ...

def runApVerify(cmdLine: Optional[Any] = ...): ...
def runIngestion(cmdLine: Optional[Any] = ...) -> None: ...
