from lsst.daf.persistence import Policy as Policy
from typing import Any

class Config:
    def __init__(self) -> None: ...
    def __getitem__(self, key: Any): ...
    def __contains__(self, key: Any): ...
