import lsst.obs.base as pexConfig
import lsst.obs.base as pipeBase
from typing import Any

class DatasetIngestConfig(pexConfig.Config):
    dataIngester: Any = ...
    dataFiles: Any = ...
    dataBadFiles: Any = ...
    calibIngester: Any = ...
    calibFiles: Any = ...
    calibBadFiles: Any = ...
    calibValidity: Any = ...
    curatedCalibPaths: Any = ...
    curatedCalibIngester: Any = ...
    refcats: Any = ...

class DatasetIngestTask(pipeBase.Task):
    ConfigClass: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def run(self, dataset: Any, workspace: Any) -> None: ...

class Gen3DatasetIngestConfig(pexConfig.Config):
    ingester: Any = ...
    visitDefiner: Any = ...
    dataFiles: Any = ...
    dataBadFiles: Any = ...

class Gen3DatasetIngestTask(pipeBase.Task):
    ConfigClass: Any = ...
    workspace: Any = ...
    dataset: Any = ...
    def __init__(self, dataset: Any, workspace: Any, *args: Any, **kwargs: Any) -> None: ...
    def run(self, processes: int = ...) -> None: ...

def ingestDataset(dataset: Any, workspace: Any) -> None: ...
def ingestDatasetGen3(dataset: Any, workspace: Any, processes: int = ...) -> None: ...
