import argparse
from typing import Any, Optional

class ApPipeParser(argparse.ArgumentParser):
    def __init__(self) -> None: ...
    class AppendOptional(argparse.Action):
        def __call__(self, parser: Any, namespace: Any, values: Any, option_string: Optional[Any] = ...) -> None: ...

def runApPipeGen2(workspace: Any, parsedCmdLine: Any, processes: int = ...): ...
def runApPipeGen3(workspace: Any, parsedCmdLine: Any, processes: int = ...): ...
