from ..detector import Detector as Detector
from .detectorCollection import DetectorCollectionBuilderBase as DetectorCollectionBuilderBase, DetectorCollectionDetectorBase as DetectorCollectionDetectorBase
from lsst.utils import TemplateMeta as TemplateMeta
from typing import Any

class DetectorCollectionBase(metaclass=TemplateMeta):
    def __iter__(self) -> Any: ...
    def __getitem__(self, key: Any): ...
    def getNameIter(self) -> None: ...
    def getIdIter(self) -> None: ...
