from lsst.obs.base import Instrument
from lsst.obs.base.gen2to3 import TranslatorFactory
from typing import Any

class DarkEnergyCamera(Instrument):
    filterDefinitions: Any = ...
    policyName: str = ...
    obsDataPackage: str = ...
    configPaths: Any = ...
    def __init__(self, **kwargs: Any) -> None: ...
    @classmethod
    def getName(cls): ...
    def getCamera(self): ...
    def register(self, registry: Any) -> None: ...
    def getRawFormatter(self, dataId: Any): ...
    def makeDataIdTranslatorFactory(self) -> TranslatorFactory: ...
