import lsst.pipe.base as pipeBase
from lsst.ip.isr import CrosstalkConfig, CrosstalkTask
from typing import Any, Optional

class DecamCrosstalkConfig(CrosstalkConfig):
    def getSourcesAndCoeffsFile(self, filename: str = ...): ...
    def getSourcesAndCoeffs(self): ...

class DecamCrosstalkTask(CrosstalkTask):
    ConfigClass: Any = ...
    def prepCrosstalk(self, dataRef: Any, crosstalk: Optional[Any] = ...): ...

class DecamCrosstalkIO(pipeBase.Task):
    ConfigClass: Any = ...
    def parseCrosstalkIOArgs(self): ...
    def runCrosstalkAlone(self) -> None: ...
