from lsst.pipe.tasks.ingestCalibs import CalibsParseTask
from typing import Any

class DecamCalibsParseTask(CalibsParseTask):
    def getInfo(self, filename: Any): ...
    def translate_ccdnum(self, md: Any): ...
    def translate_date(self, md: Any): ...
    def translate_filter(self, md: Any): ...
    def getDestination(self, butler: Any, info: Any, filename: Any): ...
