import lsst.obs.base
from lsst.obs.base.ingest import RawFileData
from lsst.pipe.tasks.ingest import IngestArgumentParser, IngestTask, ParseTask
from typing import Any

class DecamRawIngestTask(lsst.obs.base.RawIngestTask):
    def extractMetadata(self, filename: str) -> RawFileData: ...

class DecamIngestArgumentParser(IngestArgumentParser):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class DecamIngestTask(IngestTask):
    ArgumentParser: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def run(self, args: Any) -> None: ...

class DecamParseTask(ParseTask):
    expnumMapper: Any = ...
    instcalPrefix: str = ...
    dqmaskPrefix: str = ...
    wtmapPrefix: str = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def buildExpnumMapper(self, basepath: Any) -> None: ...
    def getInfo(self, filename: Any, filetype: str = ...): ...
    def getDestination(self, butler: Any, info: Any, filename: Any, filetype: str = ...): ...
