from lsst.obs.base import FitsRawFormatterBase
from typing import Any

class DarkEnergyCameraRawFormatter(FitsRawFormatterBase):
    translatorClass: Any = ...
    filterDefinitions: Any = ...
    wcsFlipX: bool = ...
    def getDetector(self, id: Any): ...
    def readMetadata(self): ...
    def readImage(self): ...

class DarkEnergyCameraCPCalibFormatter(DarkEnergyCameraRawFormatter):
    def readImage(self): ...
