from .polygon import Polygon as Polygon
from lsst.utils import continueClass as continueClass
from typing import Any, Optional

class Polygon:
    def __reduce__(self): ...
    def __iter__(self) -> Any: ...
    def __getitem__(self, i: Any): ...
    def __len__(self): ...
    def __contains__(self, point: Any): ...
    def display(self, xy0: Optional[Any] = ..., frame: int = ..., ctype: Optional[Any] = ...) -> None: ...
    def plot(self, axes: Optional[Any] = ..., **kwargs: Any): ...
