import abc
from ..cli import butler as butler
from ..cli.utils import LogCliRunner as LogCliRunner, Mocker as Mocker, clickResultMsg as clickResultMsg, mockEnvVar as mockEnvVar
from typing import Any, Optional

class CliCmdTestBase(abc.ABC, metaclass=abc.ABCMeta):
    @staticmethod
    @abc.abstractmethod
    def defaultExpected() -> Any: ...
    @staticmethod
    @abc.abstractmethod
    def command() -> Any: ...
    @property
    def cli(self): ...
    runner: Any = ...
    def setUp(self) -> None: ...
    @classmethod
    def makeExpected(cls, **kwargs: Any): ...
    def run_command(self, inputs: Any): ...
    def run_test(self, inputs: Any, expectedKwargs: Any, withTempFile: Optional[Any] = ...): ...
    def run_missing(self, inputs: Any, expectedMsg: Any) -> None: ...
    def test_help(self) -> None: ...
