from .. import Butler as Butler, Config as Config, StorageClassFactory as StorageClassFactory
from ..registry import CollectionType as CollectionType
from ..tests import MetricsExample as MetricsExample, addDatasetType as addDatasetType
from typing import Any, Optional

class ButlerTestHelper:
    def assertAstropyTablesEqual(self, tables: Any, expectedTables: Any) -> None: ...

def readTable(textTable: Any): ...

class MetricTestRepo:
    root: Any = ...
    storageClassFactory: Any = ...
    butler: Any = ...
    datasetType: Any = ...
    def __init__(self, root: Any, configFile: Any) -> None: ...
    def addDataset(self, dataId: Any, run: Optional[Any] = ..., datasetType: Optional[Any] = ...) -> None: ...
