from typing import Any, Optional

def getCallerFrame(relative: int = ...): ...
def getStackFrame(relative: int = ...): ...

class StackFrame:
    filename: Any = ...
    lineno: Any = ...
    function: Any = ...
    def __init__(self, filename: Any, lineno: Any, function: Any, content: Optional[Any] = ...) -> None: ...
    @property
    def content(self): ...
    @classmethod
    def fromFrame(cls, frame: Any): ...
    def format(self, full: bool = ...): ...

def getCallStack(skip: int = ...): ...
