from .config import Field
from typing import Any, Optional

class ChoiceField(Field):
    allowed: Any = ...
    source: Any = ...
    def __init__(self, doc: Any, dtype: Any, allowed: Any, default: Optional[Any] = ..., optional: bool = ..., deprecated: Optional[Any] = ...) -> None: ...
