import collections.abc
from .config import Field
from typing import Any, Optional

class Dict(collections.abc.MutableMapping):
    __doc__: Any = ...
    def __init__(self, config: Any, field: Any, value: Any, at: Any, label: Any, setHistory: bool = ...) -> None: ...
    history: Any = ...
    def __getitem__(self, k: Any): ...
    def __len__(self): ...
    def __iter__(self) -> Any: ...
    def __contains__(self, k: Any): ...
    def __setitem__(self, k: Any, x: Any, at: Optional[Any] = ..., label: str = ..., setHistory: bool = ...) -> None: ...
    def __delitem__(self, k: Any, at: Optional[Any] = ..., label: str = ..., setHistory: bool = ...) -> None: ...
    def __setattr__(self, attr: Any, value: Any, at: Optional[Any] = ..., label: str = ...) -> None: ...

class DictField(Field):
    DictClass: Any = ...
    keytype: Any = ...
    itemtype: Any = ...
    dictCheck: Any = ...
    itemCheck: Any = ...
    def __init__(self, doc: Any, keytype: Any, itemtype: Any, default: Optional[Any] = ..., optional: bool = ..., dictCheck: Optional[Any] = ..., itemCheck: Optional[Any] = ..., deprecated: Optional[Any] = ...) -> None: ...
    def validate(self, instance: Any) -> None: ...
    def __set__(self, instance: Any, value: Any, at: Optional[Any] = ..., label: str = ...) -> None: ...
    def toDict(self, instance: Any): ...
