from typing import Any, Optional

class Color:
    categories: Any = ...
    colors: Any = ...
    rawText: Any = ...
    def __init__(self, text: Any, category: Any) -> None: ...
    @staticmethod
    def colorize(val: Optional[Any] = ...): ...

def format(config: Any, name: Optional[Any] = ..., writeSourceLine: bool = ..., prefix: str = ..., verbose: bool = ...): ...
