from .config import Field
from typing import Any, Optional

class RangeField(Field):
    supportedTypes: Any = ...
    min: Any = ...
    max: Any = ...
    maxCheck: Any = ...
    minCheck: Any = ...
    rangeString: Any = ...
    def __init__(self, doc: Any, dtype: Any, default: Optional[Any] = ..., optional: bool = ..., min: Optional[Any] = ..., max: Optional[Any] = ..., inclusiveMin: bool = ..., inclusiveMax: bool = ..., deprecated: Optional[Any] = ...): ...
