from typing import Any, Optional

def makeConfigClass(ctrl: Any, name: Optional[Any] = ..., base: Any = ..., doc: Optional[Any] = ..., module: Optional[Any] = ..., cls: Optional[Any] = ...): ...
def wrap(ctrl: Any): ...
