from typing import Any

class BackgroundList:
    def __init__(self, *args: Any) -> None: ...
    def __getitem__(self, *args: Any): ...
    def __len__(self, *args: Any): ...
    def append(self, val: Any) -> None: ...
    def clone(self): ...
    def writeFits(self, fileName: Any, flags: int = ...) -> None: ...
    @staticmethod
    def readFits(fileName: Any, hdu: int = ..., flags: int = ...): ...
    def getImage(self): ...
    def __reduce__(self): ...
