import lsst.afw.image as pexConfig
from typing import Any, Optional

class WarperConfig(pexConfig.Config):
    warpingKernelName: Any = ...
    maskWarpingKernelName: Any = ...
    interpLength: Any = ...
    cacheSize: Any = ...
    growFullMask: Any = ...

class Warper:
    ConfigClass: Any = ...
    def __init__(self, warpingKernelName: Any, interpLength: Any = ..., cacheSize: Any = ..., maskWarpingKernelName: str = ..., growFullMask: Any = ...) -> None: ...
    @classmethod
    def fromConfig(cls, config: Any): ...
    def getWarpingKernel(self): ...
    def getMaskWarpingKernel(self): ...
    def warpExposure(self, destWcs: Any, srcExposure: Any, border: int = ..., maxBBox: Optional[Any] = ..., destBBox: Optional[Any] = ...): ...
    def warpImage(self, destWcs: Any, srcImage: Any, srcWcs: Any, border: int = ..., maxBBox: Optional[Any] = ..., destBBox: Optional[Any] = ...): ...
