import lsst.pipe.base as pexConfig
import lsst.pipe.base as pipeBase
from typing import Any, Optional

class ApPipeConfig(pexConfig.Config):
    ccdProcessor: Any = ...
    differencer: Any = ...
    diaPipe: Any = ...
    def setDefaults(self) -> None: ...
    def validate(self) -> None: ...

class ApPipeTask(pipeBase.CmdLineTask):
    ConfigClass: Any = ...
    RunnerClass: Any = ...
    def __init__(self, butler: Any, *args: Any, **kwargs: Any) -> None: ...
    def runDataRef(self, rawRef: Any, templateIds: Optional[Any] = ..., reuse: Optional[Any] = ...): ...
    def runProcessCcd(self, sensorRef: Any): ...
    def runDiffIm(self, sensorRef: Any, templateIds: Optional[Any] = ...): ...
    def runAssociation(self, sensorRef: Any): ...
