import argparse
from typing import Any, Optional

class ConfigOnlyParser(argparse.ArgumentParser):
    def __init__(self, description: Optional[Any] = ..., **kwargs: Any) -> None: ...
    def parse_args(self, args: Optional[Any] = ..., namespace: Optional[Any] = ...): ...

def makeApdb(args: Optional[Any] = ...): ...

class ConfigValueAction(argparse.Action):
    def __call__(self, parser: Any, namespace: Any, values: Any, option_string: Any) -> None: ...

class ConfigFileAction(argparse.Action):
    def __call__(self, parser: Any, namespace: Any, values: Any, option_string: Optional[Any] = ...) -> None: ...
