from lsst.pipe.base import PipelineTask, PipelineTaskConnections
from lsst.pipe.tasks.insertFakes import InsertFakesConfig
from typing import Any

class MatchApFakesConnections(PipelineTaskConnections):
    fakeCat: Any = ...
    diffIm: Any = ...
    associatedDiaSources: Any = ...
    matchedDiaSources: Any = ...

class MatchApFakesConfig(InsertFakesConfig):
    matchDistanceArcseconds: Any = ...

class MatchApFakesTask(PipelineTask):
    ConfigClass: Any = ...
    def runQuantum(self, butlerQC: Any, inputRefs: Any, outputRefs: Any) -> None: ...
    def run(self, fakeCat: Any, diffIm: Any, associatedDiaSources: Any): ...
