from lsst.obs.base import Instrument
from lsst.obs.base.gen2to3 import TranslatorFactory
from typing import Any, Optional

class HyperSuprimeCam(Instrument):
    policyName: str = ...
    obsDataPackage: str = ...
    filterDefinitions: Any = ...
    additionalCuratedDatasetTypes: Any = ...
    configPaths: Any = ...
    def __init__(self, **kwargs: Any) -> None: ...
    @classmethod
    def getName(cls): ...
    def register(self, registry: Any) -> None: ...
    def getRawFormatter(self, dataId: Any): ...
    def getCamera(self): ...
    def getBrighterFatterKernel(self): ...
    def writeAdditionalCuratedCalibrations(self, butler: Any, collection: Optional[Any] = ..., labels: Any = ...) -> None: ...
    def ingestStrayLightData(self, butler: Any, directory: Any, *, transfer: Optional[Any] = ..., collection: Optional[Any] = ..., labels: Any = ...) -> None: ...
    def makeDataIdTranslatorFactory(self) -> TranslatorFactory: ...
