from typing import Any, Optional

position: Any

def showFrames(mos: Any, frame0: int = ..., R: int = ..., subtractSky: bool = ...) -> None: ...

class MedianFilterImageWorker:
    mos: Any = ...
    medianN: Any = ...
    def __init__(self, mos: Any, medianN: Any) -> None: ...
    def __call__(self, v: Any): ...

def prepareFrames(mos: Any, frame0: int = ..., R: int = ..., medianN: int = ..., onlyVisits: Any = ..., nJob: int = ..., force: bool = ...) -> None: ...
def OLDprepareFrames(mos: Any, frame0: int = ..., R: int = ..., medianN: int = ..., onlyVisits: Any = ..., force: bool = ...) -> None: ...
def annularAverage(im: Any, nBin: int = ..., rmin: Optional[Any] = ..., rmax: Optional[Any] = ..., median: bool = ...): ...
def plotAnnularAverages(mos: Any, visits: Any, bin: int = ..., useSmoothed: bool = ..., weightByR: bool = ..., showSum: bool = ..., **kwargs: Any) -> None: ...
