import lsst.meas.base
from typing import Any, Optional

class FilterFractionPluginConfig(lsst.meas.base.SingleFramePluginConfig): ...

class FilterFractionPlugin(lsst.meas.base.SingleFramePlugin):
    ConfigClass: Any = ...
    @classmethod
    def getExecutionOrder(cls): ...
    unweightedKey: Any = ...
    weightedKey: Any = ...
    def __init__(self, config: Any, name: Any, schema: Any, metadata: Any) -> None: ...
    def measure(self, measRecord: Any, exposure: Any) -> None: ...
    def fail(self, measRecord: Any, error: Optional[Any] = ...) -> None: ...
