from lsst.pipe.tasks.ingest import IngestArgumentParser as IngestArgumentParser, IngestTask as IngestTask, ParseTask as ParseTask
from lsst.pipe.tasks.ingestCalibs import CalibsParseTask as CalibsParseTask
from typing import Any

class HscIngestArgumentParser(IngestArgumentParser): ...

class HscIngestTask(IngestTask):
    ArgumentParser: Any = ...

def datetime2mjd(date_time: Any): ...

class HscParseTask(ParseTask):
    DAY0: int = ...
    def translate_field(self, md: Any): ...
    def translate_visit(self, md: Any): ...
    def getTjd(self, md: Any): ...
    def translate_pointing(self, md: Any): ...
    CCD_MAP_COMMISSIONING_2: Any = ...
    def translate_ccd(self, md: Any): ...
    def translate_filter(self, md: Any): ...

class HscCalibsParseTask(CalibsParseTask):
    def translate_ccd(self, md: Any): ...
    def translate_filter(self, md: Any): ...
    def translate_calibDate(self, md: Any): ...
    def translate_calibVersion(self, md: Any): ...

class SuprimecamParseTask(HscParseTask):
    DAY0: int = ...
    def translate_visit(self, md: Any): ...
