from lsst.obs.base import FitsRawFormatterBase
from typing import Any

class HyperSuprimeCamRawFormatter(FitsRawFormatterBase):
    FLIP_LR: bool = ...
    FLIP_TB: bool = ...
    translatorClass: Any = ...
    filterDefinitions: Any = ...
    def getDetector(self, id: Any): ...
    def readImage(self): ...

class HyperSuprimeCamCornerRawFormatter(HyperSuprimeCamRawFormatter):
    FLIP_LR: bool = ...
    FLIP_TB: bool = ...
