from lsst.afw.image import ExposureF as ExposureF
from lsst.pipe.base import PipelineTask as PipelineTask, PipelineTaskConfig as PipelineTaskConfig, PipelineTaskConnections as PipelineTaskConnections, Struct as Struct
from typing import Any

class CalexpToCoaddTaskConnections(PipelineTaskConnections):
    calexp: Any = ...
    coadd: Any = ...

class CalexpToCoaddTaskConfig(PipelineTaskConfig): ...

class CalexpToCoaddTask(PipelineTask):
    ConfigClass: Any = ...
    def run(self, calexp: Any): ...
