from lsst.pipe.base import PipelineTask as PipelineTask, PipelineTaskConfig as PipelineTaskConfig, PipelineTaskConnections as PipelineTaskConnections, Struct as Struct
from typing import Any

class PatchSkyMapTaskConnections(PipelineTaskConnections):
    coadd: Any = ...
    inputCatalog: Any = ...
    outputCatalog: Any = ...

class PatchSkyMapTaskConfig(PipelineTaskConfig): ...

class PatchSkyMapTask(PipelineTask):
    ConfigClass: Any = ...
    def run(self, coadd: Any, inputCatalog: Any): ...
