from lsst.pipe.base import PipelineTask as PipelineTask, PipelineTaskConfig as PipelineTaskConfig, PipelineTaskConnections as PipelineTaskConnections, Struct as Struct
from typing import Any

class Test1Connections(PipelineTaskConnections):
    input: Any = ...
    output: Any = ...

class Test1Config(PipelineTaskConfig): ...

class Test1Task(PipelineTask):
    ConfigClass: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def run(self, input: Any): ...
