from lsst.daf.butler import DataCoordinate, DimensionGraph, DimensionPacker

class ObservationDimensionPacker(DimensionPacker):
    def __init__(self, fixed: DataCoordinate, dimensions: DimensionGraph) -> None: ...
    @property
    def maxBits(self) -> int: ...
    def unpack(self, packedId: int) -> DataCoordinate: ...
