import re
from lsst.daf.butler import DataCoordinate, DatasetType, FileDataset
from lsst.log import Log
from typing import Any, Callable, ClassVar, Iterable, List, Mapping, Optional, Union

class RepoWalker:
    log: Any = ...
    def __init__(self, inputs: Iterable[Union[Target, Skip]], *, fileIgnoreRegEx: Optional[re.Pattern]=..., dirIgnoreRegEx: Optional[re.Pattern]=..., log: Optional[Log]=...) -> None: ...
    Target: ClassVar[type] = ...
    Skip: ClassVar[type] = ...
    def walk(self, root: str, predicate: Optional[Callable[[DataCoordinate], bool]]) -> Mapping[DatasetType, Mapping[Optional[str], List[FileDataset]]]: ...
