import lsst.daf.persistence as pexConfig
from lsst.pipe.base import Task
from typing import Any, Optional

class MetricsControllerConfig(pexConfig.Config):
    jobFileTemplate: Any = ...
    metadataAdder: Any = ...
    measurers: Any = ...

class MetricsControllerTask(Task):
    ConfigClass: Any = ...
    measurers: Any = ...
    def __init__(self, config: Optional[Any] = ..., **kwargs: Any) -> None: ...
    def runDataRefs(self, datarefs: Any, customMetadata: Optional[Any] = ..., skipExisting: bool = ...): ...
