from typing import Any

def register(name: Any): ...
def registerMultiple(name: Any): ...

class _MultiConfigFactory:
    def __init__(self, configurableClass: Any) -> None: ...
    def __call__(self, config: Any, **kwargs: Any): ...

class MetricRegistry:
    registry: Any = ...
