import abc
import lsst.utils.tests
from typing import Any

class MetricTaskTestCase(lsst.utils.tests.TestCase, metaclass=abc.ABCMeta):
    @classmethod
    @abc.abstractmethod
    def makeTask(cls) -> Any: ...
    task: Any = ...
    taskClass: Any = ...
    def setUp(self) -> None: ...
    def testInputDatasetTypesKeys(self) -> None: ...
    def testAddStandardMetadata(self) -> None: ...
    def testCallAddStandardMetadata(self) -> None: ...
