from .jsonmixin import JsonSerializationMixin
from typing import Any, Optional

class BlobSet(JsonSerializationMixin):
    def __init__(self, blobs: Optional[Any] = ...) -> None: ...
    @classmethod
    def deserialize(cls, blobs: Optional[Any] = ...): ...
    def __getitem__(self, key: Any): ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __len__(self): ...
    def __contains__(self, key: Any): ...
    def __delitem__(self, key: Any) -> None: ...
    def __iter__(self) -> Any: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
    def keys(self): ...
    def values(self): ...
    def items(self) -> None: ...
    def insert(self, blob: Any) -> None: ...
    @property
    def json(self): ...
