from .jsonmixin import JsonSerializationMixin
from typing import Any, Optional

class QuantityAttributeMixin:
    @property
    def quantity(self): ...
    @quantity.setter
    def quantity(self, q: Any) -> None: ...
    @property
    def unit(self): ...
    @property
    def unit_str(self): ...
    @property
    def latex_unit(self): ...

class Datum(QuantityAttributeMixin, JsonSerializationMixin):
    quantity: Any = ...
    def __init__(self, quantity: Optional[Any] = ..., unit: Optional[Any] = ..., label: Optional[Any] = ..., description: Optional[Any] = ...) -> None: ...
    @classmethod
    def deserialize(cls, label: Optional[Any] = ..., description: Optional[Any] = ..., value: Optional[Any] = ..., unit: Optional[Any] = ...): ...
    @property
    def json(self): ...
    @property
    def label(self): ...
    @label.setter
    def label(self, value: Any) -> None: ...
    @property
    def description(self): ...
    @description.setter
    def description(self, value: Any) -> None: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
