from .jsonmixin import JsonSerializationMixin
from typing import Any, Optional

class Metadata(JsonSerializationMixin):
    def __init__(self, measurement_set: Any, data: Optional[Any] = ...) -> None: ...
    def __getitem__(self, key: Any): ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __delitem__(self, key: Any) -> None: ...
    def __contains__(self, key: Any): ...
    def __len__(self): ...
    def __iter__(self) -> Any: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
    def keys(self): ...
    def items(self) -> None: ...
    def update(self, data: Any) -> None: ...
    @property
    def json(self): ...
