from .jsonmixin import JsonSerializationMixin
from typing import Any, Optional

class MetadataQuery(JsonSerializationMixin):
    terms: Any = ...
    def __init__(self, terms: Optional[Any] = ...) -> None: ...
    def __call__(self, metadata: Any, arg_driven: bool = ...): ...
    def __eq__(self, other: Any) -> Any: ...
    @property
    def json(self): ...
