from typing import Any, Optional

def get_endpoint_url(api_url: Any, api_endpoint: Any, **kwargs: Any): ...
def reset_endpoint_cache() -> None: ...
def get_default_timeout(): ...
def get_default_api_version(): ...
def make_accept_header(version: Optional[Any] = ...): ...
def post(api_url: Any, api_endpoint: Any, json_doc: Optional[Any] = ..., timeout: Optional[Any] = ..., version: Optional[Any] = ..., access_token: Optional[Any] = ...): ...
def get(api_url: Any, api_endpoint: Optional[Any] = ..., api_user: Optional[Any] = ..., api_password: Optional[Any] = ..., timeout: Optional[Any] = ..., version: Optional[Any] = ...): ...
