import lsst.afw.math as interface
import lsst.afw.math as virtualDevice
from typing import Any, Optional

class Ds9Error(IOError): ...

def getXpaAccessPoint(): ...
def ds9Version(): ...

class Buffer:
    def __init__(self, size: int = ...) -> None: ...
    def set(self, size: Any, silent: bool = ...) -> None: ...
    def pushSize(self, size: int = ...) -> None: ...
    def popSize(self) -> None: ...
    def flush(self, silent: bool = ...) -> None: ...

def selectFrame(frame: Any): ...
def ds9Cmd(cmd: Optional[Any] = ..., trap: bool = ..., flush: bool = ..., silent: bool = ..., frame: Optional[Any] = ..., get: bool = ...): ...
def initDS9(execDs9: bool = ...) -> None: ...

class Ds9Event(interface.Event):
    def __init__(self, k: Any, x: Any, y: Any) -> None: ...

class DisplayImpl(virtualDevice.DisplayImpl):
    def __init__(self, display: Any, verbose: bool = ..., *args: Any, **kwargs: Any) -> None: ...
