from typing import Any, Optional

def makeImageFromArray(array: Any): ...
def makeMaskFromArray(array: Any): ...
def makeMaskedImageFromArrays(image: Any, mask: Optional[Any] = ..., variance: Optional[Any] = ...): ...
