from typing import Any, Optional

def assertImagesAlmostEqual(testCase: Any, image0: Any, image1: Any, skipMask: Optional[Any] = ..., rtol: float = ..., atol: float = ..., msg: str = ...) -> None: ...
def assertImagesEqual(*args: Any, **kwds: Any): ...
def assertMasksEqual(testCase: Any, mask0: Any, mask1: Any, skipMask: Optional[Any] = ..., msg: str = ...) -> None: ...
def assertMaskedImagesAlmostEqual(testCase: Any, maskedImage0: Any, maskedImage1: Any, doImage: bool = ..., doMask: bool = ..., doVariance: bool = ..., skipMask: Optional[Any] = ..., rtol: float = ..., atol: float = ..., msg: str = ...) -> None: ...
def assertMaskedImagesEqual(*args: Any, **kwds: Any): ...
