from lsst.obs.base import CameraMapper, MakeRawVisitInfo
from typing import Any, Optional

class Ctio0m9MakeRawVisitInfo(MakeRawVisitInfo):
    def setArgDict(self, md: Any, argDict: Any) -> None: ...
    def getDateAvg(self, md: Any, exposureTime: Any): ...

class Ctio0m9Mapper(CameraMapper):
    packageName: str = ...
    MakeRawVisitInfoClass: Any = ...
    def __init__(self, inputPolicy: Optional[Any] = ..., **kwargs: Any) -> None: ...
    def bypass_ccdExposureId(self, datasetType: Any, pythonType: Any, location: Any, dataId: Any): ...
    def bypass_ccdExposureId_bits(self, datasetType: Any, pythonType: Any, location: Any, dataId: Any): ...
    def std_raw_md(self, md: Any, dataId: Any): ...
    def std_raw(self, item: Any, dataId: Any): ...
    def std_dark(self, item: Any, dataId: Any): ...
