from lsst.obs.ctio0m9.ctio0m9Mapper import sanitize_date as sanitize_date
from lsst.pipe.tasks.ingest import ParseTask as ParseTask
from lsst.pipe.tasks.ingestCalibs import CalibsParseTask as CalibsParseTask
from typing import Any

EXTENSIONS: Any

def mjdToVisit(date_obs: Any): ...

class Ctio0m9ParseTask(ParseTask):
    def getInfo(self, filename: Any): ...
    def translate_visit(self, md: Any): ...
    def translate_imgType(self, md: Any): ...
    def translate_wavelength(self, md: Any): ...
    def translate_filter(self, md: Any): ...
    def translate_dateobs(self, md: Any): ...
    def translate_filter1(self, md: Any): ...
    def translate_filter2(self, md: Any): ...

class Ctio0m9CalibsParseTask(CalibsParseTask):
    def translate_filter(self, md: Any): ...
    def translate_calibDate(self, md: Any): ...
    def translate_ccd(self, md: Any): ...
