from lsst.daf.butler.formatters.file import FileFormatter
from typing import Any

class PackagesFormatter(FileFormatter):
    supportedWriteParameters: Any = ...
    supportedExtensions: Any = ...
    @property
    def extension(self) -> str: ...
