from typing import Any

class Dodecahedron:
    vertexVecList: Any = ...
    faceVecList: Any = ...
    def __init__(self, withFacesOnPoles: bool = ...) -> None: ...
    def getFaceCtrList(self): ...
    def getFaceCtr(self, ind: Any): ...
    def getVertices(self, ind: Any): ...
    def getFaceInd(self, vec: Any): ...
    def getWithFacesOnPoles(self): ...
