from .fits import Fits as Fits, ImageCompressionOptions as ImageCompressionOptions, ImageScalingOptions as ImageScalingOptions, ImageWriteOptions as ImageWriteOptions, compressionAlgorithmToString as compressionAlgorithmToString, scalingAlgorithmToString as scalingAlgorithmToString
from lsst.utils import continueClass as continueClass
from typing import Any

class Fits:
    def __enter__(self): ...
    def __exit__(self, cls: Any, exc: Any, traceback: Any) -> None: ...

class ImageWriteOptions: ...
class ImageCompressionOptions: ...
class ImageScalingOptions: ...
