from lsst.afw.fits.fitsLib import ImageCompressionOptions as ImageCompressionOptions, ImageWriteOptions as ImageWriteOptions, MemFileManager as MemFileManager
from typing import Any

def reduceToFits(obj: Any): ...
def unreduceFromFits(cls, data: Any, size: Any): ...
