from lsst.pex.config import Config
from typing import Any

transformRegistry: Any

class IdentityTransformConfig(Config): ...

class OneTransformConfig(Config):
    transform: Any = ...

class AffineTransformConfig(Config):
    linear: Any = ...
    translation: Any = ...

class RadialTransformConfig(Config):
    coeffs: Any = ...
    def validate(self) -> None: ...

class MultiTransformConfig(Config):
    transformDict: Any = ...

class TransformConfig(Config):
    transform: Any = ...
