import enum
from typing import Any, FrozenSet

class CollectionType(enum.IntEnum):
    RUN: int = ...
    TAGGED: int = ...
    CHAINED: int = ...
    CALIBRATION: int = ...
    @classmethod
    def all(cls: Any) -> FrozenSet[CollectionType]: ...
