import sqlalchemy
from ..core import ButlerURI, ConfigSubset
from .interfaces import Database
from typing import Any, Optional, Type, Union

class RegistryConfig(ConfigSubset):
    component: str = ...
    requiredKeys: Any = ...
    defaultConfigFile: str = ...
    def getDialect(self) -> str: ...
    def getDatabaseClass(self) -> Type[Database]: ...
    def makeDefaultDatabaseUri(self, root: str) -> Optional[str]: ...
    def replaceRoot(self, root: Optional[Union[str, ButlerURI]]) -> None: ...
    @property
    def connectionString(self) -> sqlalchemy.engine.url.URL: ...
