from typing import Any

class NameShrinker:
    maxLength: Any = ...
    hashSize: Any = ...
    def __init__(self, maxLength: int, hashSize: int=...) -> None: ...
    def shrink(self, original: str) -> str: ...
    def expand(self, shrunk: str) -> str: ...
