from .fgcmBuildStarsBase import FgcmBuildStarsBaseTask, FgcmBuildStarsConfigBase
from typing import Any, Optional

class FgcmBuildStarsConfig(FgcmBuildStarsConfigBase):
    referenceCCD: Any = ...
    checkAllCcds: Any = ...
    def setDefaults(self) -> None: ...

class FgcmBuildStarsTask(FgcmBuildStarsBaseTask):
    ConfigClass: Any = ...
    RunnerClass: Any = ...
    def findAndGroupDataRefs(self, butler: Any, dataRefs: Any): ...
    def fgcmMakeAllStarObservations(self, groupedDataRefs: Any, visitCat: Any, calibFluxApertureRadius: Optional[Any] = ..., visitCatDataRef: Optional[Any] = ..., starObsDataRef: Optional[Any] = ..., inStarObsCat: Optional[Any] = ...): ...
