from .fgcmBuildStarsBase import FgcmBuildStarsBaseTask, FgcmBuildStarsConfigBase
from typing import Any, Optional

class FgcmBuildStarsTableConfig(FgcmBuildStarsConfigBase):
    referenceCCD: Any = ...
    instFluxField: str = ...
    localBackgroundFluxField: str = ...
    apertureInnerInstFluxField: str = ...
    apertureOuterInstFluxField: str = ...
    psfCandidateName: str = ...
    def setDefaults(self) -> None: ...

class FgcmBuildStarsTableTask(FgcmBuildStarsBaseTask):
    ConfigClass: Any = ...
    RunnerClass: Any = ...
    def findAndGroupDataRefs(self, butler: Any, dataRefs: Any): ...
    def fgcmMakeAllStarObservations(self, groupedDataRefs: Any, visitCat: Any, calibFluxApertureRadius: Optional[Any] = ..., visitCatDataRef: Optional[Any] = ..., starObsDataRef: Optional[Any] = ..., inStarObsCat: Optional[Any] = ...): ...
