import lsst.geom as pexConfig
import lsst.geom as pipeBase
from typing import Any

class FgcmLoadReferenceCatalogConfig(pexConfig.Config):
    refObjLoader: Any = ...
    refFilterMap: Any = ...
    applyColorTerms: Any = ...
    colorterms: Any = ...
    referenceSelector: Any = ...
    def validate(self) -> None: ...

class FgcmLoadReferenceCatalogTask(pipeBase.Task):
    ConfigClass: Any = ...
    butler: Any = ...
    def __init__(self, butler: Any, *args: Any, **kwargs: Any) -> None: ...
    def getFgcmReferenceStarsHealpix(self, nside: Any, pixel: Any, filterList: Any, nest: bool = ...): ...
    def getFgcmReferenceStarsSkyCircle(self, ra: Any, dec: Any, radius: Any, filterList: Any): ...
