import lsst.afw.cameraGeom as pexConfig
import lsst.afw.cameraGeom as pipeBase
from typing import Any, Optional

class FgcmMakeLutParametersConfig(pexConfig.Config):
    elevation: Any = ...
    pmbRange: Any = ...
    pmbSteps: Any = ...
    pwvRange: Any = ...
    pwvSteps: Any = ...
    o3Range: Any = ...
    o3Steps: Any = ...
    tauRange: Any = ...
    tauSteps: Any = ...
    alphaRange: Any = ...
    alphaSteps: Any = ...
    zenithRange: Any = ...
    zenithSteps: Any = ...
    pmbStd: Any = ...
    pwvStd: Any = ...
    o3Std: Any = ...
    tauStd: Any = ...
    alphaStd: Any = ...
    airmassStd: Any = ...
    lambdaNorm: Any = ...
    lambdaStep: Any = ...
    lambdaRange: Any = ...

class FgcmMakeLutConfig(pexConfig.Config):
    filterNames: Any = ...
    stdFilterNames: Any = ...
    atmosphereTableName: Any = ...
    parameters: Any = ...
    def validate(self) -> None: ...

class FgcmMakeLutRunner(pipeBase.ButlerInitializedTaskRunner):
    @staticmethod
    def getTargetList(parsedCmd: Any): ...
    def __call__(self, butler: Any): ...
    def run(self, parsedCmd: Any): ...

class FgcmMakeLutTask(pipeBase.CmdLineTask):
    ConfigClass: Any = ...
    RunnerClass: Any = ...
    def __init__(self, butler: Optional[Any] = ..., **kwargs: Any) -> None: ...
    def runDataRef(self, butler: Any) -> None: ...
