from lsst.pex.config import Config
from typing import Any

class Sedboundaryterm(Config):
    primary: Any = ...
    secondary: Any = ...

class SedboundarytermDict(Config):
    data: Any = ...

class Sedterm(Config):
    primaryTerm: Any = ...
    secondaryTerm: Any = ...
    extrapolated: Any = ...
    constant: Any = ...
    primaryBand: Any = ...
    secondaryBand: Any = ...
    tertiaryBand: Any = ...
    def validate(self) -> None: ...

class SedtermDict(Config):
    data: Any = ...
