from typing import Any

alpha: Any
beta: Any
gamma: float
delta: float
K: float

def cdf_9_7(data: Any, level: Any): ...
def cdf_9_7_1d(data: Any, level: Any, axis: int = ...): ...
def icdf_9_7(data: Any, level: Any): ...
def icdf_9_7_1d(data: Any, level: Any, axis: int = ...): ...
def periodic_cdf_9_7_1d(data: Any, level: Any, axis: int = ...): ...
def periodic_icdf_9_7_1d(data: Any, level: Any, axis: int = ...): ...
def scaled_size(size: Any, level: Any): ...
