from lsst.geom import Angle
from lsst.ip.isr.straylight import StrayLightData, StrayLightTask
from typing import Any, Optional

class SubaruStrayLightTask(StrayLightTask):
    ConfigClass: Any = ...
    def readIsrData(self, dataRef: Any, rawExposure: Any): ...
    def check(self, exposure: Any): ...
    def run(self, exposure: Any, strayLightData: Any) -> None: ...

class SubaruStrayLightData(StrayLightData):
    def __init__(self, filename: Any) -> None: ...
    def evaluate(self, angle_start: Angle, angle_end: Optional[Angle]=...) -> Any: ...
