from .dateTime import DateTime as DateTime
from .propertyContainer import PropertyList as PropertyList, PropertySet as PropertySet, getPropertyListState as getPropertyListState, getPropertySetState as getPropertySetState, setPropertyListState as setPropertyListState, setPropertySetState as setPropertySetState
from typing import Any

loaderList: Any

def dt_representer(dumper: Any, data: Any): ...
def pl_representer(dumper: Any, data: Any): ...
def ps_representer(dumper: Any, data: Any): ...
def dt_constructor(loader: Any, node: Any): ...
def pl_constructor(loader: Any, node: Any) -> None: ...
def ps_constructor(loader: Any, node: Any) -> None: ...
