from .. import Butler as Butler
from ..cli.utils import sortAstropyTable as sortAstropyTable
from typing import Any

class _Table:
    dataIds: Any = ...
    def __init__(self) -> None: ...
    def add(self, dataId: Any) -> None: ...
    def getAstropyTable(self): ...

def queryDataIds(repo: Any, dimensions: Any, datasets: Any, where: Any, collections: Any): ...
