from .. import Butler as Butler
from ..cli.utils import sortAstropyTable as sortAstropyTable
from ..core.utils import globToRegex as globToRegex
from collections import namedtuple
from typing import Any, Optional

_RefInfo = namedtuple('RefInfo', 'datasetRef uri')

class _Table:
    datasetRefs: Any = ...
    def __init__(self) -> None: ...
    def add(self, datasetRef: Any, uri: Optional[Any] = ...) -> None: ...
    def getAstropyTable(self, datasetTypeName: Any): ...

def queryDatasets(repo: Any, glob: Any, collections: Any, where: Any, find_first: Any, show_uri: Any): ...
