from ._geom import Angle as Angle, AngleUnit as AngleUnit
from lsst.utils import continueClass as continueClass
from typing import Any

class AngleUnit:
    def __mul__(self, other: Any): ...
    def __rmul__(self, other: Any): ...
    def __reduce__(self): ...
