from lsst.utils import TemplateMeta
from typing import Any

class CoordinateExpr(metaclass=TemplateMeta):
    TEMPLATE_PARAMS: Any = ...
    __reduce__: Any = ...

class Extent(metaclass=TemplateMeta):
    TEMPLATE_PARAMS: Any = ...
    TEMPLATE_DEFAULTS: Any = ...
    __reduce__: Any = ...

ExtentI: Any
ExtentD: Any

class Point(metaclass=TemplateMeta):
    TEMPLATE_PARAMS: Any = ...
    TEMPLATE_DEFAULTS: Any = ...
    __reduce__: Any = ...

PointI: Any
PointD: Any
