from ._geom import arcseconds as arcseconds
from typing import Any, Optional

def extraMsg(msg: Any): ...
def assertAnglesAlmostEqual(testCase: Any, ang0: Any, ang1: Any, maxDiff: Any = ..., ignoreWrap: bool = ..., msg: str = ...) -> None: ...
def assertPairsAlmostEqual(testCase: Any, pair0: Any, pair1: Any, maxDiff: float = ..., msg: str = ...) -> None: ...
def assertPairListsAlmostEqual(testCase: Any, list0: Any, list1: Any, maxDiff: float = ..., msg: Optional[Any] = ...) -> None: ...
def assertSpherePointsAlmostEqual(testCase: Any, sp0: Any, sp1: Any, maxSep: Any = ..., msg: str = ...) -> None: ...
def assertSpherePointListsAlmostEqual(testCase: Any, splist0: Any, splist1: Any, maxSep: Any = ..., msg: Optional[Any] = ...) -> None: ...
def assertBoxesAlmostEqual(testCase: Any, box0: Any, box1: Any, maxDiff: float = ..., msg: str = ...) -> None: ...
