import networkx as nx
from typing import Any, Optional, Set

DatasetTypeName: Any

class _DatasetTrackerElement:
    inputs: Set[_U] = ...
    output: Optional[_U] = ...
    def __init__(self, inputs: Any, output: Any) -> None: ...

class _DatasetTracker:
    def __init__(self) -> None: ...
    def addInput(self, key: _T, value: _U) -> Any: ...
    def addOutput(self, key: _T, value: _U) -> Any: ...
    def getInputs(self, key: _T) -> Set[_U]: ...
    def getOutput(self, key: _T) -> Optional[_U]: ...
    def getAll(self, key: _T) -> Set[_U]: ...
    def makeNetworkXGraph(self) -> nx.DiGraph: ...
    def keys(self) -> Set[_T]: ...
