from typing import Any, Optional

def refraction(wavelength: Any, elevation: Any, observatory: Any, weather: Optional[Any] = ...): ...
def differentialRefraction(wavelength: Any, wavelengthRef: Any, elevation: Any, observatory: Any, weather: Optional[Any] = ...): ...
