import lsst.pex.config as pexConfig
from typing import Any

class DiaSourceAnalystConfig(pexConfig.Config):
    srcBadMaskPlanes: Any = ...
    fBadPixels: Any = ...
    fluxPolarityRatio: Any = ...
    nPolarityRatio: Any = ...
    nMaskedRatio: Any = ...
    nGoodRatio: Any = ...

class DiaSourceAnalyst:
    config: Any = ...
    log: Any = ...
    bitMask: int = ...
    def __init__(self, config: Any) -> None: ...
    def countDetected(self, mask: Any): ...
    def countMasked(self, mask: Any): ...
    def countPolarity(self, mask: Any, pixels: Any): ...
    def testSource(self, source: Any, subMi: Any): ...
