from typing import Any

def backgroundSubtract(config: Any, maskedImages: Any): ...
def writeKernelCellSet(kernelCellSet: Any, psfMatchingKernel: Any, backgroundModel: Any, outdir: Any) -> None: ...
def sourceToFootprintList(candidateInList: Any, templateExposure: Any, scienceExposure: Any, kernelSize: Any, config: Any, log: Any): ...

class NbasisEvaluator:
    psfMatchConfig: Any = ...
    psfFwhmPixTc: Any = ...
    psfFwhmPixTnc: Any = ...
    def __init__(self, psfMatchConfig: Any, psfFwhmPixTc: Any, psfFwhmPixTnc: Any) -> None: ...
    def __call__(self, kernelCellSet: Any, log: Any): ...
