from typing import Any, Optional

def makeKernelBasisList(config: Any, targetFwhmPix: Optional[Any] = ..., referenceFwhmPix: Optional[Any] = ..., basisDegGauss: Optional[Any] = ..., metadata: Optional[Any] = ...): ...
def generateAlardLuptonBasisList(config: Any, targetFwhmPix: Optional[Any] = ..., referenceFwhmPix: Optional[Any] = ..., basisDegGauss: Optional[Any] = ..., metadata: Optional[Any] = ...): ...
