from lsst.verify.tasks import MetricConfig, MetricConnections, MetricTask
from typing import Any

class NumberSciSourcesMetricConnections(MetricConnections):
    sources: Any = ...

class NumberSciSourcesMetricConfig(MetricConfig): ...

class NumberSciSourcesMetricTask(MetricTask):
    ConfigClass: Any = ...
    def run(self, sources: Any): ...

class FractionDiaSourcesToSciSourcesMetricConnections(MetricTask.ConfigClass.ConnectionsClass):
    sciSources: Any = ...
    diaSources: Any = ...

class FractionDiaSourcesToSciSourcesMetricConfig(MetricTask.ConfigClass): ...

class FractionDiaSourcesToSciSourcesMetricTask(MetricTask):
    ConfigClass: Any = ...
    def run(self, sciSources: Any, diaSources: Any): ...
