import lsst.pipe.base as pexConfig
from .psfMatch import PsfMatchTask
from typing import Any

class ModelPsfMatchConfig(pexConfig.Config):
    kernel: Any = ...
    doAutoPadPsf: Any = ...
    autoPadPsfTo: Any = ...
    padPsfBy: Any = ...
    def setDefaults(self) -> None: ...

class ModelPsfMatchTask(PsfMatchTask):
    ConfigClass: Any = ...
    kConfig: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def run(self, exposure: Any, referencePsfModel: Any, kernelSum: float = ...): ...
