from lsst.ip.isr.vignette import VignetteConfig as VignetteConfig
from lsst.pex.config import ConfigField as ConfigField, Field as Field, ListField as ListField
from lsst.pipe.drivers.constructCalibs import CalibCombineConfig as CalibCombineConfig, CalibCombineTask as CalibCombineTask
from typing import Any

class HscFlatCombineConfig(CalibCombineConfig):
    vignette: Any = ...
    badAmpCcdList: Any = ...
    badAmpList: Any = ...
    maskPlane: Any = ...
    def validate(self) -> None: ...

class HscFlatCombineTask(CalibCombineTask):
    ConfigClass: Any = ...
    def run(self, sensorRefList: Any, *args: Any, **kwargs: Any): ...
    def maskVignetting(self, mask: Any, detector: Any) -> None: ...
    def maskBadAmps(self, mask: Any, detector: Any) -> None: ...
