from lsst.afw.cameraGeom import PupilFactory as PupilFactory
from lsst.geom import Angle as Angle, degrees as degrees
from typing import Any

class HscPupilFactory(PupilFactory):
    def __init__(self, visitInfo: Any, pupilSize: Any, npix: Any, doCenter: bool = ...) -> None: ...
    telescopeDiameter: float = ...
    def getPupil(self, point: Any): ...
