from .baseSkyMap import BaseSkyMap
from typing import Any, Optional

class CachingSkyMap(BaseSkyMap):
    def __init__(self, numTracts: Any, config: Optional[Any] = ..., version: int = ...) -> None: ...
    def __reduce__(self): ...
    def __iter__(self) -> Any: ...
    def __len__(self): ...
    def __getitem__(self, index: Any): ...
    def generateTract(self, index: Any) -> None: ...
