from .cachingSkyMap import CachingSkyMap
from typing import Any

class DiscreteSkyMapConfig(CachingSkyMap.ConfigClass):
    raList: Any = ...
    decList: Any = ...
    radiusList: Any = ...
    def validate(self) -> None: ...

class DiscreteSkyMap(CachingSkyMap):
    ConfigClass: Any = ...
    def __init__(self, config: Any, version: int = ...) -> None: ...
    def generateTract(self, index: Any): ...
    def updateSha1(self, sha1: Any) -> None: ...
