from .baseSkyMap import BaseSkyMap
from typing import Any, Optional

class DodecaSkyMapConfig(BaseSkyMap.ConfigClass):
    withTractsOnPoles: Any = ...
    tractOverlap: float = ...
    patchBorder: int = ...
    pixelScale: Any = ...
    patchInnerDimensions: Any = ...
    projection: str = ...
    def setDefaults(self) -> None: ...

class DodecaSkyMap(BaseSkyMap):
    ConfigClass: Any = ...
    def __init__(self, config: Optional[Any] = ...) -> None: ...
    def findTract(self, coord: Any): ...
    def getVersion(self): ...
    def getWithTractsOnPoles(self): ...
    def updateSha1(self, sha1: Any) -> None: ...
