from .baseSkyMap import BaseSkyMap
from typing import Any, Optional

class EquatSkyMapConfig(BaseSkyMap.ConfigClass):
    numTracts: Any = ...
    decRange: Any = ...
    projection: str = ...
    def setDefaults(self) -> None: ...

class EquatSkyMap(BaseSkyMap):
    ConfigClass: Any = ...
    def __init__(self, config: Optional[Any] = ...) -> None: ...
    def getVersion(self): ...
    def updateSha1(self, sha1: Any) -> None: ...
