from .cachingSkyMap import CachingSkyMap
from .tractInfo import TractInfo
from typing import Any

class DummyHealpy:
    def __getattr__(self, name: Any, e: Any = ...) -> None: ...

class HealpixTractInfo(TractInfo):
    def __init__(self, nSide: Any, ident: Any, nest: Any, patchInnerDimensions: Any, patchBorder: Any, ctrCoord: Any, tractOverlap: Any, wcs: Any) -> None: ...

class HealpixSkyMapConfig(CachingSkyMap.ConfigClass):
    log2NSide: Any = ...
    nest: Any = ...
    rotation: int = ...
    def setDefaults(self) -> None: ...

class HealpixSkyMap(CachingSkyMap):
    ConfigClass: Any = ...
    numAngles: int = ...
    def __init__(self, config: Any, version: int = ...) -> None: ...
    def findTract(self, coord: Any): ...
    def generateTract(self, index: Any): ...
    def updateSha1(self, sha1: Any) -> None: ...
