from typing import Any

def makeSkyPolygonFromBBox(bbox: Any, wcs: Any): ...

class PatchInfo:
    def __init__(self, index: Any, innerBBox: Any, outerBBox: Any) -> None: ...
    def getIndex(self): ...
    def getInnerBBox(self): ...
    def getOuterBBox(self): ...
    def getInnerSkyPolygon(self, tractWcs: Any): ...
    def getOuterSkyPolygon(self, tractWcs: Any): ...
    def __eq__(self, rhs: Any) -> Any: ...
    def __ne__(self, rhs: Any) -> Any: ...
