from .cachingSkyMap import CachingSkyMap
from typing import Any

class RingsSkyMapConfig(CachingSkyMap.ConfigClass):
    numRings: Any = ...
    raStart: Any = ...

class RingsSkyMap(CachingSkyMap):
    ConfigClass: Any = ...
    def __init__(self, config: Any, version: int = ...) -> None: ...
    def getRingIndices(self, index: Any): ...
    def generateTract(self, index: Any): ...
    def findTract(self, coord: Any): ...
    def findAllTracts(self, coord: Any): ...
    def findTractPatchList(self, coordList: Any): ...
    def updateSha1(self, sha1: Any) -> None: ...
