from lsst.ctrl.orca.CondorJobs import CondorJobs as CondorJobs
from lsst.ctrl.orca.CondorWorkflowMonitor import CondorWorkflowMonitor as CondorWorkflowMonitor
from lsst.ctrl.orca.WorkflowLauncher import WorkflowLauncher as WorkflowLauncher
from typing import Any

class CondorWorkflowLauncher(WorkflowLauncher):
    prodConfig: Any = ...
    wfConfig: Any = ...
    runid: Any = ...
    localStagingDir: Any = ...
    dagFile: Any = ...
    monitorConfig: Any = ...
    def __init__(self, prodConfig: Any, wfConfig: Any, runid: Any, localStagingDir: Any, dagFile: Any, monitorConfig: Any) -> None: ...
    def cleanUp(self) -> None: ...
    workflowMonitor: Any = ...
    def launch(self, statusListener: Any): ...
