from typing import Any, Optional

class CondorJobs:
    def __init__(self) -> None: ...
    def submitJob(self, condorFile: Any): ...
    def waitForJobToRun(self, num: Any, extramsg: Optional[Any] = ...): ...
    def waitForAllJobsToRun(self, numList: Any) -> None: ...
    def condorSubmitDag(self, filename: Any): ...
    def killCondorId(self, cid: Any) -> None: ...
    def isJobAlive(self, cid: Any): ...
