import threading
from lsst.ctrl.orca.CondorJobs import CondorJobs as CondorJobs
from lsst.ctrl.orca.WorkflowMonitor import WorkflowMonitor as WorkflowMonitor
from lsst.ctrl.orca.multithreading import SharedData as SharedData
from typing import Any

class CondorWorkflowMonitor(WorkflowMonitor):
    condorDagId: Any = ...
    monitorConfig: Any = ...
    def __init__(self, condorDagId: Any, monitorConfig: Any) -> None: ...
    class _WorkflowMonitorThread(threading.Thread):
        condorDagId: Any = ...
        monitorConfig: Any = ...
        def __init__(self, parent: Any, condorDagId: Any, monitorConfig: Any) -> None: ...
        def run(self) -> None: ...
    def startMonitorThread(self) -> None: ...
    def stopWorkflow(self, urgency: Any) -> None: ...
