from typing import Any

class DatabaseConfigurator:
    runid: Any = ...
    databaseConfig: Any = ...
    prodConfig: Any = ...
    def __init__(self, runid: Any, databaseConfig: Any, prodConfig: Any) -> None: ...
    def setup(self, provSetup: Any) -> None: ...
