from typing import Any

class Directories:
    config: Any = ...
    runid: Any = ...
    shortname: Any = ...
    patdata: Any = ...
    defroot: Any = ...
    def __init__(self, dirConfig: Any, shortName: Any, runId: str = ...) -> None: ...
    def getDefaultRootDir(self): ...
    def getDefaultRunDir(self): ...
    def getNamedDirectory(self, name: Any): ...
    def getDirs(self): ...
