from typing import Any, Optional

class FileWaiter:
    remoteNode: Any = ...
    fileListName: Any = ...
    remoteFileWaiter: Any = ...
    def __init__(self, remoteNode: Any, remoteFileWaiter: Any, fileListName: Any, logger: Optional[Any] = ...) -> None: ...
    def waitForFirstFile(self) -> None: ...
    def waitForAllFiles(self) -> None: ...
