from lsst.ctrl.orca.CondorWorkflowMonitor import CondorWorkflowMonitor as CondorWorkflowMonitor
from lsst.ctrl.orca.PegasusJobs import PegasusJobs as PegasusJobs
from lsst.ctrl.orca.WorkflowLauncher import WorkflowLauncher as WorkflowLauncher
from typing import Any

class PegasusWorkflowLauncher(WorkflowLauncher):
    prodConfig: Any = ...
    wfConfig: Any = ...
    runid: Any = ...
    localStagingDir: Any = ...
    sitesXMLFile: Any = ...
    transformFile: Any = ...
    daxFile: Any = ...
    monitorConfig: Any = ...
    def __init__(self, prodConfig: Any, wfConfig: Any, runid: Any, localStagingDir: Any, sitesXMLFile: Any, transformFile: Any, daxFile: Any, monitorConfig: Any) -> None: ...
    def cleanUp(self) -> None: ...
    workflowMonitor: Any = ...
    def launch(self, statusListener: Any): ...
