from http.server import BaseHTTPRequestHandler
from typing import Any

class ServiceHandler(BaseHTTPRequestHandler):
    version: str = ...
    production: Any = ...
    parent: Any = ...
    runid: Any = ...
    def setParent(self, parent: Any, runid: Any) -> None: ...
    def do_DELETE(self) -> None: ...
    def writeError(self, status: Any, message: Any) -> None: ...
