from typing import Any

class StatusListener:
    def __init__(self) -> None: ...
    def workflowFailed(self, name: Any, errorName: Any, errmsg: Any, response: Any, pipelineName: Any) -> None: ...
    def workflowShutdown(self, name: Any) -> None: ...
    def workflowStarted(self, name: Any) -> None: ...
    def workflowWaiting(self, name: Any) -> None: ...
