from lsst.ctrl.orca.multithreading import SharedData as SharedData
from typing import Any

class WorkflowMonitor:
    def __init__(self) -> None: ...
    def addStatusListener(self, statusListener: Any) -> None: ...
    def handleRequest(self, request: Any) -> None: ...
    def handleFailure(self) -> None: ...
    def isRunning(self): ...
    def isDone(self): ...
    def stopWorkflow(self, urgency: Any) -> None: ...
