from lsst.ctrl.orca.WorkflowMonitor import WorkflowMonitor as WorkflowMonitor
from typing import Any

class WorkflowLauncher:
    wfConfig: Any = ...
    def __init__(self, wfConfig: Any) -> None: ...
    def cleanUp(self) -> None: ...
    workflowMonitor: Any = ...
    def launch(self, statusListener: Any): ...
