from lsst.ctrl.orca.NamedClassFactory import NamedClassFactory as NamedClassFactory
from typing import Any, Optional

class WorkflowConfigurator:
    class ConfigGroup:
        configName: Any = ...
        config: Any = ...
        configNumber: Any = ...
        globalOffset: Any = ...
        def __init__(self, name: Any, config: Any, number: Any, offset: Any) -> None: ...
        def getConfig(self): ...
        def getConfigName(self): ...
        def getConfigNumber(self): ...
        def getGlobalOffset(self): ...
    runid: Any = ...
    prodConfig: Any = ...
    wfConfig: Any = ...
    def __init__(self, runid: Any, prodConfig: Any, wfConfig: Any) -> None: ...
    def configure(self, provSetup: Any, workflowVerbosity: Optional[Any] = ...): ...
    def createDatabaseConfigurator(self, databaseConfig: Any): ...
    def expandConfigs(self, wfShortName: Any): ...
