from lsst.ctrl.orca.NamedClassFactory import NamedClassFactory as NamedClassFactory
from lsst.ctrl.orca.exceptions import MultiIssueConfigurationError as MultiIssueConfigurationError
from lsst.ctrl.orca.multithreading import SharedData as SharedData
from typing import Any, Optional

class WorkflowManager:
    name: str = ...
    runid: Any = ...
    repository: Any = ...
    wfConfig: Any = ...
    prodConfig: Any = ...
    urgency: int = ...
    def __init__(self, name: Any, runid: Any, repository: Any, prodConfig: Any, wfConfig: Any) -> None: ...
    def getName(self): ...
    def runWorkflow(self, statusListener: Any): ...
    def stopWorkflow(self, urgency: Any) -> None: ...
    def cleanUp(self) -> None: ...
    def configure(self, provSetup: Optional[Any] = ..., workflowVerbosity: Optional[Any] = ...): ...
    def createConfigurator(self, runid: Any, repository: Any, wfName: Any, wfConfig: Any, prodConfig: Any): ...
    def isRunning(self): ...
    def isDone(self): ...
    def isRunnable(self): ...
    def checkConfiguration(self, care: int = ..., issueExc: Optional[Any] = ...) -> None: ...
    def getWorkflowName(self): ...
    def getNodeCount(self): ...
