from typing import Any

def assembleAmplifierImage(destImage: Any, rawImage: Any, amplifier: Any) -> None: ...
def assembleAmplifierRawImage(destImage: Any, rawImage: Any, amplifier: Any) -> None: ...
def makeUpdatedDetector(ccd: Any): ...
