from typing import Any

def addDetectorBuilderFromConfig(cameraBuilder: Any, detectorConfig: Any, amplifiers: Any, focalPlaneToField: Any): ...
def makeCameraFromPath(cameraConfig: Any, ampInfoPath: Any, shortNameFunc: Any, pupilFactoryClass: Any = ...): ...
def makeCameraFromAmpLists(cameraConfig: Any, ampListDict: Any, pupilFactoryClass: Any = ...): ...
