import lsst.geom as pexConfig
from typing import Any

class DetectorConfig(pexConfig.Config):
    transformDict: Any = ...
    name: Any = ...
    id: Any = ...
    bbox_x0: Any = ...
    bbox_y0: Any = ...
    bbox_x1: Any = ...
    bbox_y1: Any = ...
    detectorType: Any = ...
    physicalType: Any = ...
    serial: Any = ...
    offset_x: Any = ...
    offset_y: Any = ...
    refpos_x: Any = ...
    refpos_y: Any = ...
    yawDeg: Any = ...
    pitchDeg: Any = ...
    rollDeg: Any = ...
    pixelSize_x: Any = ...
    pixelSize_y: Any = ...
    transposeDetector: Any = ...
    crosstalk: Any = ...
    def getCrosstalk(self, numAmps: Any): ...
    @property
    def bbox(self): ...
    @property
    def offset(self): ...
    @property
    def refPos(self): ...
    @property
    def orientation(self): ...
    @property
    def pixelSize(self): ...

class CameraConfig(pexConfig.Config):
    detectorList: Any = ...
    transformDict: Any = ...
    name: Any = ...
    plateScale: Any = ...
    radialCoeffs: Any = ...
