from .._butlerConfig import ButlerConfig
from .config import ConfigSubset
from .datasets import DatasetRef, DatasetType
from .dimensions import DimensionUniverse
from .storageClass import StorageClass
from typing import Any, Union

class CompositesConfig(ConfigSubset):
    component: str = ...
    requiredKeys: Any = ...
    defaultConfigFile: str = ...
    def validate(self) -> None: ...

class CompositesMap:
    config: Any = ...
    def __init__(self, config: Union[str, ButlerConfig, CompositesConfig], universe: DimensionUniverse) -> None: ...
    def shouldBeDisassembled(self, entity: Union[DatasetRef, DatasetType, StorageClass]) -> bool: ...
