from .config import Config
from .configSupport import LookupKey
from .datasets import DatasetRef, DatasetType
from .dimensions import DimensionUniverse
from .exceptions import ValidationError
from .storageClass import StorageClass
from typing import Any, Optional, Set, Union

class ConstraintsValidationError(ValidationError): ...
class ConstraintsConfig(Config): ...

class Constraints:
    matchAllKey: Any = ...
    config: Any = ...
    def __init__(self, config: Optional[Union[ConstraintsConfig, str]], universe: DimensionUniverse) -> None: ...
    def isAcceptable(self, entity: Union[DatasetRef, DatasetType, StorageClass]) -> bool: ...
    def getLookupKeys(self) -> Set[LookupKey]: ...
