from .location import Location
from .storageClass import StorageClass
from typing import Any, Mapping, Optional

class FileDescriptor:
    location: Any = ...
    storageClass: Any = ...
    parameters: Any = ...
    def __init__(self, location: Location, storageClass: StorageClass, readStorageClass: Optional[StorageClass]=..., parameters: Optional[Mapping[str, Any]]=...) -> None: ...
    @property
    def readStorageClass(self) -> StorageClass: ...
