import sqlalchemy
from typing import Any, ClassVar, Optional, TypeVar

T = TypeVar('T')

class SimpleQuery:
    columns: Any = ...
    where: Any = ...
    def __init__(self) -> None: ...
    class Select:
        Or: ClassVar[Any]
    def join(self, table: sqlalchemy.sql.FromClause, *, onclause: Optional[sqlalchemy.sql.ColumnElement]=..., isouter: bool=..., full: bool=..., **kwargs: Any) -> None: ...
    def combine(self) -> sqlalchemy.sql.Select: ...
    @property
    def from_(self) -> sqlalchemy.sql.FromClause: ...
    def copy(self) -> SimpleQuery: ...
