import astropy.utils.exceptions
import yaml
from typing import Any

def astropy_to_nsec(astropy_time: astropy.time.Time) -> int: ...
def nsec_to_astropy(time_nsec: int) -> astropy.time.Time: ...
def times_equal(time1: astropy.time.Time, time2: astropy.time.Time, precision_nsec: float=...) -> bool: ...

class _AstropyTimeToYAML:
    yaml_tag: str = ...
    @classmethod
    def to_yaml(cls: Any, dumper: yaml.Dumper, data: astropy.time.Time) -> Any: ...
    @classmethod
    def from_yaml(cls: Any, loader: yaml.SafeLoader, node: yaml.ScalarNode) -> astropy.time.Time: ...
