from lsst.utils import TemplateMeta
from typing import Any, Optional

VariancePixel: Any

class MaskedImage(metaclass=TemplateMeta):
    def set(self, value: Any, mask: Optional[Any] = ..., variance: Optional[Any] = ...) -> None: ...
    def getArrays(self): ...
    def convertF(self): ...
    def convertD(self): ...
    def __reduce__(self): ...
    readFitsWithOptions: Any = ...
    writeFitsWithOptions: Any = ...
